### PR TITLE
Give ATen errors backtraces

### LINKED ISSUE #6055: Better debug info from C++
### Problem Description

The autograd engine launches 1 + #gpus threads to execute functions. This has the downside that when an exception gets thrown in any of the functions running in one of these threads, we currently have to catch that exception and rethrow it from the main thread. The unfortunate consequence of this is that all stack traces point back to [the line where the exception is rethrown](https://github.com/pytorch/pytorch/blob/b37aa2bf0e1d0fc62a7a924c0b50fe06870c1bce/torch/csrc/autograd/engine.cpp#L358).

### Possible Solutions

1. Change the autograd engine to have a mode where it executes all tasks on the main thread,
2. Use custom exception objects everywhere and capture either:
    1. The `__LINE__` and `__FILE__` info or,
    2. The full call stack (likely preferred) using [the kernel's relevant facilities for this](http://man7.org/linux/man-pages/man3/backtrace.3.html)
3. Tell people to use `catch throw`

### Goal

In the end, the experience should really be as smooth as possible for the end user. `catch throw` will work most of the time, but people might not know about it or it may not help with debugging. Having to change the autograd execution and re-run the graph is a bit annoying. Giving the full call stack in the exception is likely the most user-friendly option, but `__LINE__` et al. is a good start.

CC @ebetica

### PR DESCRIPTION
**Pull request by goldsborough**
This PR builds on top of #6059 to now add backtraces to errors inside ATen. This greatly improves the debugging experience for our C++ users. It works towards #6055.

## Example

Before:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  hello
./run.sh: line 1: 786857 Aborted                 (core dumped) LD_LIBRARY_PATH="torch/lib/:./build/lib.linux-x86_64-3.6/torch/:/home/psag/local/miniconda/lib" ./e
```

After:

```
terminate called after throwing an instance of 'at::Error'
  what():  hello (embedding_backward at ../src/ATen/native/Embedding.cpp:38)
frame #0: at::Type::embedding_backward(at::Tensor const&, at::Tensor const&, long, long, bool, bool) const + 0x27 (0x7f7bc5e15f07 in torch/lib/libATen.so.1)
frame #1: torch::autograd::VariableType::embedding_backward(at::Tensor const&, at::Tensor const&, long, long, bool, bool) const + 0x1fd (0x7f7bc1519fbd in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #2: torch::autograd::generated::EmbeddingBackward::apply(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0xf0 (0x7f7bc15ec490 in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: torch::autograd::Engine::evaluate_function(torch::autograd::FunctionTask&) + 0x3db (0x7f7bc14aa69b in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #4: torch::autograd::Engine::thread_main(torch::autograd::GraphTask*) + 0xe5 (0x7f7bc14ab665 in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #5: torch::autograd::Engine::thread_init(int) + 0x5e (0x7f7bc14a7dce in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)

./run.sh: line 1: 685721 Aborted                 (core dumped) LD_LIBRARY_PATH="torch/lib/:./build/lib.linux-x86_64-3.6/torch/:/home/psag/local/miniconda/lib" ./e
```

## Implementation

The implementation of this feature relies entirely on glibc/libstdc++/libcxx features and requires no extra dependencies. It uses the `backtrace()` family of glibc function to get call stack information and then uses `__cxa_demangle` from libstc++/libcxx to demangle symbol names. It works well across dynamic library boundaries and works on both Linux and macOS. Windows has a pretty good API to implement this, but is not a priority now. I've put some pointers on how to implement it on Windows if we get a request.

@apaszke @cpuhrsch @colesbury 

CC @ebetica 

Fixes #6055

### CODE REVIEW

File: aten/src/ATen/Error.h [hunk 1]
```diff
@@ -5,14 +5,164 @@
...
+  // `backtrace_symbols` takes the return addresses obtained from `backtrace()`
+  // and fetches string representations of each stack. Unfortunately it doesn't
+  // return a struct of individual pieces of information but a concatenated
+  // string, so we'll have to parse the string after.
+  char** raw_symbols = ::backtrace_symbols(callstack.data(), callstack.size());
+  std::vector<std::string> symbols(raw_symbols, raw_symbols + callstack.size());
+
+  // The array returned by `backtrace_symbols` is malloc'd and must be manually
+  // freed, but not the strings inside the array.
+  free(raw_symbols);
```
Comment (apaszke) [inline aten/src/ATen/Error.h]: Let's use a `unique_ptr` to manage this

File: aten/src/ATen/Error.h [hunk 2]
```diff
@@ -5,14 +5,164 @@
...
+  // standard C++ (Itanium ABI) mangling scheme. This is the case for `main` or
+  // `clone` for example, so the mangled name is a fine default.
+  if (status == 0) {
+    frame.function_name = demangled_function_name;
+  } else {
+    frame.function_name = mangled_function_name;
+  }
+
+  // `__cxa_demangle` returns a malloc'd string that we have to free ourselves.
+  free(demangled_function_name);
```
Comment (apaszke) [inline aten/src/ATen/Error.h]: Can you use `unique_ptr` for this? There are allocations that can fail between those lines

File: aten/src/ATen/Error.h [hunk 3]
```diff
@@ -5,14 +5,164 @@
...
+  // The backtrace string goes into here.
+  std::ostringstream stream;
+
+  for (size_t frame_number = 0; frame_number < callstack.size();
+       ++frame_number) {
+    const auto frame = parse_frame_information(symbols[frame_number]);
+
+    // These are usually uninteresting frames below `main` or `clone` with
+    // limited debugging information.
+    if (frame.function_name.empty()) {
```
Comment (apaszke) [inline aten/src/ATen/Error.h]: Can we print sth like `<5 frames without debug info>` at the end? In case there would be any errors in the parsing code, that would at least give you a hint that it's this conditioned that get triggered, and it's not like the stack is all messed up

File: aten/src/ATen/Error.h [hunk 4]
```diff
@@ -5,14 +5,164 @@
...
+  std::string mangled_function_name;
+
+#ifdef __GLIBCXX__
+  // In GLIBCXX, `frame_string` follows the pattern
+  // `<object-file>(<mangled-function-name>+<offset-into-function>)
+  // [<return-address>]`
+
+  const auto function_name_start = frame_string.find('(') + 1;
+  const auto offset_start = frame_string.find('+', function_name_start) + 1;
+  const auto offset_end = frame_string.find(')', offset_start);
```
Comment (apaszke) [inline aten/src/ATen/Error.h]: Can you check that they're not `npos`?

File: aten/src/ATen/Error.h [hunk 5]
```diff
@@ -5,14 +5,164 @@
...
+  input_stream >> skip >> frame.object_file >> skip >> mangled_function_name >>
+      skip >> frame.offset_into_function;
+#endif
+
+  int status = -1;
+  // This function will demangle the mangled function name into a more human
+  // readable format, e.g. _Z1gv -> g().
+  // More information:
+  // https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/libsupc%2B%2B/cxxabi.h
+  char* demangled_function_name = abi::__cxa_demangle(
```
Comment (apaszke) [inline aten/src/ATen/Error.h]: How portable are those `abi::` functions?

File: aten/src/ATen/Error.h [hunk 6]
```diff
@@ -5,14 +5,164 @@
...
+  frame.object_file = frame_string.substr(0, function_name_start - 1);
+  frame.offset_into_function =
+      frame_string.substr(offset_start, offset_end - offset_start);
+
+  // NOTE: We don't need to parse the return address because
+  // we already have it from the call to `backtrace()`.
+
+  mangled_function_name = frame_string.substr(
+      function_name_start, (offset_start - 1) - function_name_start);
+#else
```
Comment (apaszke) [inline aten/src/ATen/Error.h]: Is there a libcxx specific macro we could check? It would be nicer to avoid assume that everything that's not gcc is clang, and at least have a readable `#error`, or better raise a `#warning` and handle this by returning the whole string without parsing.

**Review by apaszke — COMMENTED** [review]
Looks good in general, but some things could be improved.

File: aten/src/ATen/Error.h (hunk 2 above)
Comment (goldsborough) [reply aten/src/ATen/Error.h]: Yeah good point, should've thought of this

File: aten/src/ATen/Error.h (hunk 5 above)
Comment (goldsborough) [reply aten/src/ATen/Error.h]: `<cxxabi.h>` exists in both libc++ and libstdc++, so should work in all compilers we care about (including icc)

File: aten/src/ATen/Error.h (hunk 6 above)
Comment (goldsborough) [reply aten/src/ATen/Error.h]: Looks like `_LIBCPP_VERSION` https://stackoverflow.com/questions/31657499/how-to-detect-stdlib-libc-in-the-preprocessor?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

File: aten/src/ATen/Error.h (hunk 3 above)
Comment (goldsborough) [reply aten/src/ATen/Error.h]: Ok

**Comment by goldsborough** [comment]
Ok, so now for the low-level functions it shows `<unknown function>`:

```
terminate called after throwing an instance of 'at::Error'
  what():  hello (embedding_backward at ../src/ATen/native/Embedding.cpp:38)
frame #0: at::Type::embedding_backward(at::Tensor const&, at::Tensor const&, long, long, bool, bool) const + 0x27 (0x7f2620c67377 in torch/lib/libATen.so.1)
frame #1: torch::autograd::VariableType::embedding_backward(at::Tensor const&, at::Tensor const&, long, long, bool, bool) const + 0x1fd (0x7f261c35796d in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #2: torch::autograd::generated::EmbeddingBackward::apply(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0xf0 (0x7f261c42ca40 in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: torch::autograd::Engine::evaluate_function(torch::autograd::FunctionTask&) + 0x3db (0x7f261c2e8efb in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #4: torch::autograd::Engine::thread_main(torch::autograd::GraphTask*) + 0xe5 (0x7f261c2e9ec5 in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #5: torch::autograd::Engine::thread_init(int) + 0x5e (0x7f261c2e664e in ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0xafc5c (0x7f261aaf5c5c in /home/psag/local/miniconda/lib/libstdc++.so.6)
frame #7: <unknown function> + 0x7e25 (0x7f2616133e25 in /lib64/libpthread.so.0)
frame #8: clone + 0x6d (0x7f261a26734d in /lib64/libc.so.6)

./run.sh: line 1: 1042594 Aborted                 (core dumped) LD_LIBRARY_PATH="torch/lib/:./build/lib.linux-x86_64-3.6/torch/:/home/psag/local/miniconda/lib" ./e
```

and if something were to fail during parsing we fall back to whatever `backtrace_symbols` (the glibc function) returns:

```
terminate called after throwing an instance of 'at::Error'
  what():  hello (embedding_backward at ../src/ATen/native/Embedding.cpp:38)
frame #0: torch/lib/libATen.so.1(_ZNK2at4Type18embedding_backwardERKNS_6TensorES3_llbb+0x27) [0x7fafbe95c7c7]
frame #1: ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so(_ZNK5torch8autograd12VariableType18embedding_backwardERKN2at6TensorES5_llbb+0x1fd) [0x7fafba04d8ad]
frame #2: ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so(_ZN5torch8autograd9generated17EmbeddingBackward5applyERKSt6vectorINS0_8VariableESaIS4_EE+0xf0) [0x7fafba122a30]
frame #3: ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so(_ZN5torch8autograd6Engine17evaluate_functionERNS0_12FunctionTaskE+0x3db) [0x7fafb9fdee3b]
frame #4: ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so(_ZN5torch8autograd6Engine11thread_mainEPNS0_9GraphTaskE+0xe5) [0x7fafb9fdfe05]
frame #5: ./build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so(_ZN5torch8autograd6Engine11thread_initEi+0x5e) [0x7fafb9fdc58e]
frame #6: /home/psag/local/miniconda/lib/libstdc++.so.6(+0xafc5c) [0x7fafb87ebc5c]
frame #7: /lib64/libpthread.so.0(+0x7e25) [0x7fafb3e29e25]
frame #8: /lib64/libc.so.6(clone+0x6d) [0x7fafb7f5d34d]
```

File: aten/src/ATen/Error.h [hunk 7]
```diff
@@ -1,18 +1,202 @@
...
+  FrameInformation frame;
+
+  // This is the function name in the CXX ABI mangled format, e.g. something
+  // like _Z1gv. Reference:
+  // https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling
+  std::string mangled_function_name;
+
+#if defined(__GLIBCXX__)
+  // In GLIBCXX, `frame_string` follows the pattern
+  // `<object-file>(<mangled-function-name>+<offset-into-function>)
```
Comment (apaszke) [inline aten/src/ATen/Error.h]: I wonder if we could use `std::regex_match` to simplify this 🤔

**Review by apaszke — APPROVED** [review]
Looks great!
