### PR TITLE
Fix memory leak introduced by 72e8190

### LINKED ISSUE #1455: Memory leak?
For replication, I use [word_language_model](https://github.com/pytorch/examples/tree/master/word_language_model)
```
 python main.py --cuda --emsize 1500 --nhid 1500 --dropout 0.65 --epochs 40
```

Errors
```
THCudaCheck FAIL file=/home/mktran/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 163, in <module>
    train()
  File "main.py", line 136, in train
    loss.backward()
  File "/home/mktran/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 144, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "/home/mktran/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 279, in _do_backward
    result = super(NestedIOFunction, self)._do_backward(gradients, retain_variables)
  File "/home/mktran/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 287, in backward
    result = self.backward_extended(*nested_gradients)
  File "/home/mktran/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 319, in backward_extended
    grad_weight = [tuple(w.new().resize_as_(w) for w in layer_weight) for layer_weight in weight]
  File "/home/mktran/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 319, in <genexpr>
    grad_weight = [tuple(w.new().resize_as_(w) for w in layer_weight) for layer_weight in weight]
RuntimeError: cuda runtime error (2) : out of memory at /home/mktran/pytorch/torch/lib/THC/generic/THCStorage.cu:66
```

### PR DESCRIPTION
**Pull request by apaszke**
Fixes #1455.

### CODE REVIEW

File: torch/csrc/autograd/python_function.cpp [hunk 1]
```diff
@@ -1017,11 +1017,11 @@ std::shared_ptr<PyFunction> THPFunction_asFunction(THPFunction* self)
   if (!self) {
     return std::shared_ptr<PyFunction>();
   }
-  Py_INCREF((PyObject*)self);
 
   auto ptr = self->cdata_ptr.lock();
   if (ptr) return ptr;
 
+  Py_INCREF((PyObject*)self);
```
Comment (soumith) [inline torch/csrc/autograd/python_function.cpp]: in the interest of actually understanding the PR:

why are you increfing self?

Comment (apaszke) [inline torch/csrc/autograd/python_function.cpp]: Because the `shared_ptr` uses the `Decref` as the deleter. Once all shared_ptrs are freed, it's `operator()` will be called and will revert this incref.

Comment (apaszke) [inline torch/csrc/autograd/python_function.cpp]: And Decref will be called only once **all shared_ptrs are freed**, not after destructing each of them (as the code before the commit suggested).

**Review by soumith — APPROVED** [review]
