### PR TITLE
Unify error checking for tensor.index_copy_

### LINKED ISSUE #1777: index_copy inconsistent behavior on CPU and GPU
`index_copy` has inconsistent behaviors for the shape of the tensor which is used to copy on CPU and GPU. In following examples, `index_copy` raises an error on CPU due to the invalid shape of `y`, but it works well on GPU for same tensors `x`, `y`, `z`.
```
In [1]: import torch

In [2]: from torch.autograd import Variable

In [3]: x = torch.ones(3,1)

In [4]: y = torch.Tensor([4])

In [5]: z = torch.LongTensor([2])

In [6]: x.index_copy_(0, z, y)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-a1189d076165> in <module>()
----> 1 x.index_copy_(0, z, y)

RuntimeError: cannot select on a vector at /users1/xwgeng/pytorch/torch/lib/TH/generic/THTensor.c:403

In [7]: x = x.cuda()

In [8]: y = y.cuda()

In [9]: z = z.cuda()

In [10]: x.index_copy_(0, z, y)
Out[10]: 

 1
 1
 4
[torch.cuda.FloatTensor of size 3x1 (GPU 0)]
```
The pytorch version is `0.1.12+d7db75c`

### PR DESCRIPTION
**Pull request by zou3519**
Fixes #1777

Previously, there was a bug where index_copy on CUDA would not error out if the shape of the source slice (in dimension 0) is not equal to the shape of the destination slice (in the specified dimension).
For example,

```
x = torch.zeros(3, 1)
t = torch.arange(3)
index = torch.LongTensor([2, 1, 0])
x.index_copy_(0, index, t) # x has slizes of size (1, 1) in dimension 0 but t has zero-dim slices in dimension 0.
```

would work on CUDA but not on CPU. This PR changes it so that both the CPU and CUDA paths use the same error checking so that the above code will error out on both CPU and CUDA.

### CODE REVIEW

**Comment by soumith** [comment]
lots of failing tests

File: aten/src/ATen/native/Indexing.cpp [hunk 1]
```diff
@@ -250,4 +250,49 @@ Tensor & index_put_(Tensor & self, TensorList indices, const Tensor & value) {
   return src.put_(linearIndex, expandedValue);
 }
 
+Tensor & index_copy_(Tensor & self, int64_t dim, const Tensor & index, const Tensor & source) {
+  dim = maybe_wrap_dim(dim, self.dim());
+
+  if (index.dim() >= 2) {
+    runtime_error(
```
Comment (fmassa) [inline aten/src/ATen/native/Indexing.cpp]: should we `throw std::runtime_error` to be consistent with the code below?

Comment (zou3519) [reply aten/src/ATen/native/Indexing.cpp]: It's probably easier to change the std::runtime_error below to a call to `runtime_error` (which calls std::runtime_error). I'll change that.

Comment (zou3519) [reply aten/src/ATen/native/Indexing.cpp]: Nevermind, I remember the reason why I wrote it like this. The `runtime_error` here is cleaner because it takes a printf-style string, and the code below throws `std::runtime_error` because the string stream creates a string of some sort (which is not the `char*` `runtime_error` expects as its first argument.

**Review by ssnl — APPROVED** [review]
LGTM
