### PR TITLE
Fix build without numpy

### LINKED ISSUE #3046: PyTorch build requires Numpy now
When I don't have a working numpy dependency detected (due to unrelated shenanigans), the build fails with this:

```
-- Building version 0.2.0+803afd5
running egg_info
writing torch.egg-info/PKG-INFO
writing dependency_links to torch.egg-info/dependency_links.txt
writing requirements to torch.egg-info/requires.txt
writing top-level names to torch.egg-info/top_level.txt
reading manifest file 'torch.egg-info/SOURCES.txt'
writing manifest file 'torch.egg-info/SOURCES.txt'
running build_ext
-- NumPy not found

....


/private/home/ezyang/pytorch/torch/csrc/generic/Tensor.cpp: In function ‘THCudaTensor* THCPFloatTensor_fromNumpy(PyObject*)’:
/private/home/ezyang/pytorch/torch/csrc/generic/Tensor.cpp:159:3: error: ‘PyArrayObject’ was not declared in this scope
   PyArrayObject *array = (PyArrayObject*)numpy_array;
   ^
```

And then a big pile of related errors.

CC @colesbury @gchanan

### PR DESCRIPTION
**Pull request by lantiga**
This PR fixes #3046

The condition at https://github.com/pytorch/pytorch/blame/master/torch/csrc/generic/Tensor.cpp#L150

```
#if defined(NUMPY_TYPE_ENUM) || defined(THC_GENERIC_FILE)
```
was evaluating to true in the case of a CUDA build without NumPy. As a bit of background, `NUMPY_TYPE_ENUM` is undefined for CUDA builds.

The condition can safely be replaced with
```
#if defined(NUMPY_TYPE_ENUM) || (defined(WITH_NUMPY) && defined(THC_GENERIC_FILE))
```

### CODE REVIEW

File: torch/csrc/generic/Tensor.cpp [hunk 1]
```diff
@@ -147,7 +148,7 @@ static void THPTensor_(setInconsistentDepthError)(std::vector<size_t> &sizes,
   THPUtils_setError(error.c_str());
 }
 
-#if defined(NUMPY_TYPE_ENUM) || defined(THC_GENERIC_FILE)
+#if defined(NUMPY_TYPE_ENUM) || (defined(WITH_NUMPY) && defined(THC_GENERIC_FILE))
```
Comment (apaszke) [inline torch/csrc/generic/Tensor.cpp]: Why does THC_GENERIC_FILE even appear in this condition? It seems unnecessary

**Review by apaszke — APPROVED** [review]
