### PR TITLE
BatchNorm fallback to THNN when eps < CUDNN_BN_MIN_EPSILON

### LINKED ISSUE #1623: incompatibility between Pytorch 0.1.12 and cuda 8.0.61/cudnn 5.1.10 ?
Hi,

I have two linux servers. My code works in one machine but not the other. In the one that it doesn't work, the error message is: `RuntimeError: CUDNN_STATUS_BAD_PARAM` occured during batch normalization( convolution is fine). Also, the same code works in CPU but not in GPU. 

I guess this problem is mainly related to GPU libraries like cuda or cudnn. *The one that doesn't work has the following configurations*:
- Nvidia driver 375.26
- cuda 8.0.61
- cudnn 5.1.10

*While in the one it does work*, I have the following configurations:
- Nvidia driver 367.48
- cuda 8.0.44
- cudnn 5.1.5

TensorFlow can run in the above environment flawless though. So I am wondering if this is caused by the incompatibility between PyTorch 0.1.12 and cuda 8.0.61/cudnn 5.1.10 ?

### PR DESCRIPTION
**Pull request by soumith**
fixes https://github.com/pytorch/pytorch/issues/1623

### CODE REVIEW

File: torch/csrc/autograd/functions/batch_normalization.cpp [hunk 1]
```diff
@@ -17,6 +17,10 @@ namespace torch { namespace autograd {
 
 using thpp::Tensor;
 
+#ifndef CUDNN_BN_MIN_EPSILON
+#define CUDNN_BN_MIN_EPSILON 0
```
Comment (fmassa) [inline torch/csrc/autograd/functions/batch_normalization.cpp]: According to https://github.com/pytorch/pytorch/issues/1623#issuecomment-303766744 , shouldn't it be something like `1e-5` or `1e-4` ?

Comment (soumith) [inline torch/csrc/autograd/functions/batch_normalization.cpp]: if pytorch is not compiled with CUDNN, then this variable wont be defined. If this wont be defined, we can define it as 0, because use_cudnn will be False and we will be using THNN anyways.
