### PR TITLE
Make sparse (new) functions conform that storage is not NULL

### LINKED ISSUE #3367: Empty cuda sparse tensor storage not initialized correctly
This causes `get_device` to not work properly on newly created empty sparse tensors. In the example below, both `get_device` should print 1 instead.
```
>>> with torch.cuda.device(1):
...   x = torch.cuda.sparse.FloatTensor()  # has to be empty size
...
>>> x.get_device()
-1
>>> x
FloatTensor of size  with indices:
[torch.cuda.LongTensor with no dimension]
and values:
[torch.cuda.FloatTensor with no dimension]

>>> x.get_device()
0
```

### PR DESCRIPTION
**Pull request by ssnl**
Fixes #3367 .

### CODE REVIEW

File: torch/csrc/generic/SparseTensor.cpp [hunk 1]
```diff
@@ -108,12 +127,12 @@ static PyObject * THSPTensor_(pynew)(PyTypeObject *type, PyObject *args, PyObjec
...
   if (num_args == 1 && THPUtils_checkLong(first_arg)) {
     long size = THPUtils_unpackLong(first_arg);
-    self->cdata = THSTensor_(newWithSize1d)(LIBRARY_STATE size);
+    self->cdata = THSTensor_(_newWithSize1d)(size);
   }
   // torch.SparseTensor(torch.Size sizes)
   else if (num_args == 1 && THPSize_Check(first_arg)) {
     THLongStoragePtr sizes(THPUtils_unpackSize(first_arg));
-    self->cdata = THSTensor_(newWithSize)(LIBRARY_STATE sizes.get());
+    self->cdata = THSTensor_(_newWithSize)(sizes.get());
```
Comment (apaszke) [inline torch/csrc/generic/SparseTensor.cpp]: are these functions necessary? There's another call to `initStorage` below

Comment (SsnL) [reply torch/csrc/generic/SparseTensor.cpp]: Ah I see! I assumed that this file was following `Tensor.cpp`. Updating now.

**Review by apaszke — APPROVED** [review]
