### PR TITLE
[ONNX] Relax constant_fold gather with indices rank > 1

### LINKED ISSUE #66786: torch.onnx.export fails to export Hugging Face BERT with meaningful weight name
## 🐛 Bug

When exporting ONNX format for BERT of Hugging Face implementation, some weight names will become numbers instead of a meaningful name. (but the inference result is correct)

E.g., for the [`nn.Linear` in `BertSelfAttention`](https://github.com/huggingface/transformers/blob/4334095c3269d5cd08d9353e67f5f1dec2aae459/src/transformers/models/bert/modeling_bert.py#L239-L241), `bias` can be generated correctly, such as `encoder.layer.0.attention.self.key.bias`, while the name of `weight` become some number.

Additionally, I found that it works well with `do_constant_folding=False`.

## To Reproduce

1. Run `test.py`

```python
# test.py

import torch
import onnx
from transformers import BertConfig, BertModel


def main():
    model = BertModel(BertConfig(num_hidden_layers=1))
    model.eval()

    input_ids = torch.randint(30522, (1, 512), dtype=torch.long)

    onnx_model_path = 'net.onnx'
    torch.onnx.export(model, input_ids, onnx_model_path, export_params=True,
                      opset_version=13, verbose=False, input_names=['input'],
                      output_names=['output1', 'output2'],
                      )

    model = onnx.load(onnx_model_path)
    weights = model.graph.initializer
    for w in weights:
        print(w.name, w.dims)


main()
```

```
$ python3 test.py
[W shape_type_inference.cpp:419] Warning: Constant folding in symbolic shape inference fails: index_select(): Index is supposed to be a vector
Exception raised from index_select_out_cpu_ at ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:758 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7eff9ae4fa22 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: at::native::index_select_out_cpu_(at::Tensor const&, long, at::Tensor const&, at::Tensor&) + 0x2a9 (0x7effdea5f199 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #2: at::native::index_select_cpu_(at::Tensor const&, long, at::Tensor const&) + 0x60 (0x7effdea61bf0 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x1a03d12 (0x7effdf1d6d12 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #4: at::redispatch::index_select(c10::DispatchKeySet, at::Tensor const&, long, at::Tensor const&) + 0xb4 (0x7effdf0590d4 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x3013df1 (0x7effe07e6df1 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x3014245 (0x7effe07e7245 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: at::index_select(at::Tensor const&, long, at::Tensor const&) + 0x14e (0x7effdee77ece in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: torch::jit::onnx_constant_fold::runTorchBackendForOnnx(torch::jit::Node const*, std::vector<at::Tensor, std::allocator<at::Tensor> >&, int) + 0x1b50 (0x7efff1a2bf00 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0xaecf7e (0x7efff1a68f7e in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: torch::jit::ONNXShapeTypeInference(torch::jit::Node*, std::map<std::string, c10::IValue, std::less<std::string>, std::allocator<std::pair<std::string const, c10::IValue> > > const&, int) + 0x906 (0x7efff1a6dd36 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0xaf49e4 (0x7efff1a709e4 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0xa70c00 (0x7efff19ecc00 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0x5011ee (0x7efff147d1ee in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #43: __libc_start_main + 0xe7 (0x7efff455ebf7 in /lib/x86_64-linux-gnu/libc.so.6)
 (function ComputeConstantFolding)
[W shape_type_inference.cpp:419] Warning: Constant folding in symbolic shape inference fails: index_select(): Index is supposed to be a vector
Exception raised from index_select_out_cpu_ at ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:758 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7eff9ae4fa22 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: at::native::index_select_out_cpu_(at::Tensor const&, long, at::Tensor const&, at::Tensor&) + 0x2a9 (0x7effdea5f199 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #2: at::native::index_select_cpu_(at::Tensor const&, long, at::Tensor const&) + 0x60 (0x7effdea61bf0 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x1a03d12 (0x7effdf1d6d12 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #4: at::redispatch::index_select(c10::DispatchKeySet, at::Tensor const&, long, at::Tensor const&) + 0xb4 (0x7effdf0590d4 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x3013df1 (0x7effe07e6df1 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x3014245 (0x7effe07e7245 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: at::index_select(at::Tensor const&, long, at::Tensor const&) + 0x14e (0x7effdee77ece in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: torch::jit::onnx_constant_fold::runTorchBackendForOnnx(torch::jit::Node const*, std::vector<at::Tensor, std::allocator<at::Tensor> >&, int) + 0x1b50 (0x7efff1a2bf00 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0xaecf7e (0x7efff1a68f7e in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: torch::jit::ONNXShapeTypeInference(torch::jit::Node*, std::map<std::string, c10::IValue, std::less<std::string>, std::allocator<std::pair<std::string const, c10::IValue> > > const&, int) + 0x906 (0x7efff1a6dd36 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0xaf49e4 (0x7efff1a709e4 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0xa70c00 (0x7efff19ecc00 in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0x5011ee (0x7efff147d1ee in /home/wenxh/siahuattan/bert-benchmark/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #40: __libc_start_main + 0xe7 (0x7efff455ebf7 in /lib/x86_64-linux-gnu/libc.so.6)
 (function ComputeConstantFolding)
embeddings.position_ids [1, 512]
embeddings.word_embeddings.weight [30522, 768]
embeddings.position_embeddings.weight [512, 768]
embeddings.token_type_embeddings.weight [2, 768]
embeddings.LayerNorm.weight [768]
embeddings.LayerNorm.bias [768]
encoder.layer.0.attention.self.query.bias [768]
encoder.layer.0.attention.self.key.bias [768]
encoder.layer.0.attention.self.value.bias [768]
encoder.layer.0.attention.output.dense.bias [768]
encoder.layer.0.attention.output.LayerNorm.weight [768]
encoder.layer.0.attention.output.LayerNorm.bias [768]
encoder.layer.0.intermediate.dense.bias [3072]
encoder.layer.0.output.dense.bias [768]
encoder.layer.0.output.LayerNorm.weight [768]
encoder.layer.0.output.LayerNorm.bias [768]
pooler.dense.weight [768, 768]
pooler.dense.bias [768]
237 [1]
238 [1]
239 [1]
240 [1]
241 [768, 768]
242 [768, 768]
243 [1]
244 [1]
245 [768, 768]
246 [1]
247 [1]
248 [1]
249 [1]
250 [1]
251 [768, 768]
252 [768, 3072]
253 [3072, 768]
```

## Expected behavior

I think the name of the weight can be generated correctly as the name for `bias` is good even with the default setting `do_constant_folding=True`.

## Environment

```
PyTorch version: 1.9.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.15.5
Libc version: glibc-2.27

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-1056-azure-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.9.1
[conda] numpy                     1.21.2                   pypi_0    pypi
```

### PR DESCRIPTION
**Pull request by BowenBao**
Fixes #66786.

`index_select` only supports `index` of 1-D tensor. `ONNX::Gather` allows `index` to have rank `q`. Abort constant folding `ONNX::Gather` if `index` rank is larger than 1.

### CODE REVIEW

File: torch/csrc/jit/passes/onnx/constant_fold.cpp [hunk 1]
```diff
@@ -462,17 +462,17 @@ c10::optional<at::Tensor> runTorchBackendForOnnx(
     // It needs to be adjusted (+= dim sizes) for aten op
     axis += axis < 0 ? inputTensorValues[0].sizes().size() : 0;
     at::Tensor indices = inputTensorValues[1];
+    auto q = indices.dim();
+    // Cases where rank of indices > 1 are not currently supported.
```
Comment (garymm) [inline torch/csrc/jit/passes/onnx/constant_fold.cpp:466]:
```suggestion
    // at::index_select only supports indices with rank <= 1.
    // See https://pytorch.org/docs/master/generated/torch.index_select.html
```

File: test/onnx/test_pytorch_onnx_onnxruntime.py [hunk 2]
```diff
@@ -3654,12 +3654,14 @@ class GatherModule(torch.nn.Module):
             def __init__(self):
                 super(GatherModule, self).__init__()
                 self.register_buffer("weight", torch.ones(5))
+                self.embed = torch.nn.Embedding(8, 3)
```
Comment (garymm) [inline test/onnx/test_pytorch_onnx_onnxruntime.py:3657]: Please add some comments explaining:
1. How does this test relate to onnx::Gather and constant folding.
2. How does torch.nn.Embedding specifically relate to it. That is what condition is this meant to test for.

**Review by garymm — APPROVED** [review]
Once you've updated the comments and CI passes feel free to merge.
Thanks!
