### PR TITLE
Fix CPU torch.multinomial with noncontiguous prob tensor

### LINKED ISSUE #5062: Potential bug when sampling from categorical distribution
Hi,

I would like to sample from a categorical distribution where the probabilities passed are the columns of a tensor p_dG:

```
G = 3
D = 2
p_dG = torch.Tensor(G, D)
p_dG[:, 0] = torch.Tensor([0.1, 0.8, 0.1])
p_dG[:, 1] = torch.Tensor([0.1, 0.8, 0.1])

z_list = []
p_dg = p_dG[:, 0]
print(p_dg)
dis_Z = dis.Categorical(p_dg)
for _ in range(250):
    z = dis_Z.sample()
    z_list.append(z)

z = torch.cat(z_list, dim=0)

true_z_np = z.numpy()
v, c = np.unique(true_z_np, return_counts=True)
print(v)
print(c)
```

The output from `print(c)` is `[ 29  25 196]`. So the distribution is completely off since the bulk of the observations should be equal to 1 (instead of being equal to 2).

In contrast, the following code works as expected:
```
z_list = []
dis_Z = dis.Categorical(torch.Tensor([0.1, 0.8, 0.1]))
for _ in range(250):
    z = dis_Z.sample()
    z_list.append(z)

z = torch.cat(z_list, dim=0)
true_z_np = z.numpy()
v, c = np.unique(true_z_np, return_counts=True)
print(v)
print(c)
```

Is this a bug or am I missing something?

I am using:
- OS: macOS High Sierra
- PyTorch version: 0.3.0
- How you installed PyTorch (conda, pip, source): conda
- Python version: Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) 
- CUDA/cuDNN version: --
- GPU models and configuration: --
- GCC version (if compiling from source): --

Thanks!

### PR DESCRIPTION
**Pull request by ssnl**
The CPU code previously uses `resize2d` which does not safely preserve data when input is not contiguous. This PR changes it to `unsqueeze1d` in both CPU and GPU functions, and add strided support for the two functions. As a result, `distributions.Categorical` now doesn't need to call `contiguous()` when the probabilities are not batched.

Also in this PR are 
1. updated tests for `torch.multinomial`,
2. updated doc for `distrbutions.OneHotCategorical` and `distrbutions.Categorical`, and
3. shape tests for `distrbutions.OneHotCategorical` and `distrbutions.Categorical` in unbatched mode.

Fixes #5062 

cc @neerajprad @alicanb for `distributions.*` changes review.

### CODE REVIEW

File: aten/src/TH/generic/THTensor.h [hunk 1]
```diff
@@ -76,6 +76,9 @@ TH_API THTensor *THTensor_(newExpand)(THTensor *tensor, THLongStorage *size);
 TH_API void THTensor_(expand)(THTensor *r, THTensor *tensor, THLongStorage *size);
 TH_API void THTensor_(expandNd)(THTensor **rets, THTensor **ops, int count);
 
+// resize* methods simplit resize the storage. So they may not retain the current data at current indices.
```
Comment (soumith) [inline aten/src/TH/generic/THTensor.h]: *simplit

File: aten/src/TH/generic/THTensor.h [hunk 2]
```diff
@@ -76,6 +76,9 @@ TH_API THTensor *THTensor_(newExpand)(THTensor *tensor, THLongStorage *size);
...
+// This is especially likely to happen when the tensor is not contiguous. In general, if you still need the
+// values, unless you are doing some size and stride tricks, do not use reize*.
```
Comment (soumith) [inline aten/src/TH/generic/THTensor.h]: reize*

File: aten/src/THC/generic/THCTensor.h [hunk 3]
```diff
@@ -73,6 +73,9 @@ THC_API THCTensor *THCTensor_(newExpand)(THCState *state, THCTensor *tensor, THL
 THC_API void THCTensor_(expand)(THCState *state, THCTensor *r, THCTensor *tensor, THLongStorage *sizes);
 THC_API void THCTensor_(expandNd)(THCState *state, THCTensor **rets, THCTensor **ops, int count);
 
+// resize* methods simplit resize the storage. So they may not retain the current data at current indices.
```
Comment (soumith) [inline aten/src/THC/generic/THCTensor.h]: same typos here too

**Review by soumith — CHANGES_REQUESTED** [review]
minor typo changes needed.

code looks good and correct

File: aten/src/THC/generic/THCTensor.h (hunk 3 above)
Comment (SsnL) [reply aten/src/THC/generic/THCTensor.h]: lol thanks!

**Review by soumith — APPROVED** [review]

**Review by neerajprad — APPROVED** [review]
Thanks for the doc fixes, and adding on the unbatched params tests. Looks great!
