### PR TITLE
Fix for non-contiguous from_numpy

### LINKED ISSUE #484: torch.from_numpy mysteriously fails for noncontiguous numpy arrays
Repro:
```python
import torch
import numpy as np

x = np.zeros((125,))      
for i in range(125):      
    x[i] = i              
x.shape = (5, 5, 5)       
x = x[:,1]

print(x)                  
print(torch.from_numpy(x))
```

Strides seem to be copied correctly, and the first row is also ok. All other rows are garbage.

### PR DESCRIPTION
**Pull request by apaszke**
Fixes #484.

### CODE REVIEW

File: torch/csrc/generic/Tensor.cpp [hunk 1]
```diff
@@ -95,18 +95,14 @@ static void THPTensor_(setInconsistentDepthError)(std::vector<size_t> &sizes,
...
-      &THNumpyArrayAllocator,
-      new NumpyArrayAllocator(numpy_array));
 
   // Numpy and Torch disagree on empty tensors. In Torch, an empty
   // tensor is a tensor with zero dimensions. In Numpy, an empty tensor
   // keeps its shape, but has 0 as the size of one of the dimensions.
   // So we'll convert all Numpy tensors of 0 elements to empty Torch tensors.
   if (PyArray_SIZE(array) != 0) {
     auto ndim = PyArray_NDIM(array);
+    size_t storage_size = 1;
```
Comment (colesbury) [inline torch/csrc/generic/Tensor.cpp]: Why is this initialized to 1 instead of 0?

**Review by colesbury — COMMENTED** [review]
I'm confused about why storage_size starts at 1 but otherwise LGTM

File: torch/csrc/generic/Tensor.cpp (hunk 1 above)
Comment (colesbury) [inline torch/csrc/generic/Tensor.cpp]: OK, @apaszke explained this to me. strides * (sizes-1) is the offset of the last element. The storage size has to be the largest offset + 1.
