### PR TITLE
Fix convolution type mismatch error message

### LINKED ISSUE #5808: Misleading message: "RuntimeError: Input type (Variable) and weight type (Variable) should be the same"
It took me quite a while to figure out what this message means (it was my very first model):
```
RuntimeError: Input type (Variable) and weight type (Variable) should be the same
```
It appears when input variable is on GPU and weight is on CPU.  Here is a minimal code to replicate the error:
```
filters = torch.randn(8,4,3,3)
inputs = torch.randn(1,4,5,5)
F.conv2d(inputs.cuda(), filters, padding=1)
```
If one removes .cuda() everything starts to work fine. 

I wasn't able to find anything on google when I searched for the phrase above so I've thought It make sense to report it as an issue so that next person may have more luck. I'm leaving it open in case you want to improve the message, but I will understand if you close it. Either way is ok and should help other newbies.

Environment details:
- PyTorch version: 0.4.0a0+cdd0feb,
- CUDA/cuDNN version: I've used .Dockerfile to compile it

### PR DESCRIPTION
**Pull request by zou3519**
Fixes #5808 

Does two main things:
1. Fix convolution type mismatch error message
2. Whenever we have a C++ Variable, don't report it as a Variable on the python side

### Test Plan
run script
image

### CODE REVIEW

File: torch/csrc/Exceptions.cpp [hunk 1]
```diff
@@ -32,6 +32,38 @@ std::string processErrorMsg(std::string str) {
 
   // Translate Aten types to their respective pytorch ones
   std::vector<std::pair<std::string, std::string>> changes {
+    {"Variable[SparseCUDAByteType]", "torch.cuda.sparse.ByteTensor"},
```
Comment (zou3519) [inline torch/csrc/Exceptions.cpp]: This is getting really out of hand. Suggestions on how to make this more maintainable are welcome! 

I didn't really want to generate all of this as a part of the codegen.

Comment (apaszke) [reply torch/csrc/Exceptions.cpp]: We don't need the tensor strings anymore, right?

Comment (colesbury) [reply torch/csrc/Exceptions.cpp]: I think we still might need them because some ATen functions operate on unpacked tensors

**Review by colesbury — APPROVED** [review]
