### PR TITLE
Fix error message for cat-ing zero-dim tensors

### LINKED ISSUE #5552: RuntimeError: dimension specified as 0 but tensor has no dimensions
My code run well under torch 0.2, however, the following error occurs when I use torch 0.3.1, why?

Traceback (most recent call last):
  File "../train.py", line 149, in <module>
    loss.backward()
  File "/home/jxliu/.local/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jxliu/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: dimension specified as 0 but tensor has no dimensions

### PR DESCRIPTION
**Pull request by zou3519**
Fixes #5552

cc @gchanan

### CODE REVIEW

**Comment by zou3519** [comment]
Okay this should be good for reviewing now. Today I learned that `IntList` is not the same thing as `std::vector<int64_t>`.

**Comment by apaszke** [comment]
@zou3519 I think in our code `*List` is usually `at::ArrayRef<*>`, while `*_list` is really `std::vector<*>`. I agree it's not great 😄

File: tools/autograd/templates/Functions.cpp [hunk 1]
```diff
@@ -364,17 +364,23 @@ Tensor unsqueeze_to(const Tensor & self, int64_t dim, IntList sizes) {
...
+  }
   std::vector<Tensor> grad_inputs(sizes.size());
   int64_t accumulate = 0;
   for (size_t i = 0; i < sizes.size(); ++i) {
-    auto size = sizes[i];
-    accumulate += size;
-    if (size == 0) {
+    auto& shape = sizes[i];
+    // If input was empty tensor, gradInput should be empty tensor.
+    if (shape[0] == 0) {
```
Comment (gchanan) [inline tools/autograd/templates/Functions.cpp]: shape == {0} seems better, will be easier to find/replace when we support full empty shapes.

File: tools/autograd/load_derivatives.py [hunk 2]
```diff
@@ -294,10 +294,10 @@ def saved_variables(formula, args):
...
             'type': 'int64_t',
         }),
-        # replace to_arg_sizes(self, 2) with self_argsizes_2
-        (r'to_arg_sizes\({}, (\w+)\)', {
-            'suffix': lambda m: '_sizes_{}'.format(*m.groups()),
-            'type': 'IntList',
+        # replace to_args_sizes(self) with self_args_sizes
+        (r'to_args_sizes\({}\)', {
+            'suffix': '_args_sizes',
+            'type': 'std::vector<std::vector<int64_t>>',
```
Comment (gchanan) [inline tools/autograd/load_derivatives.py]: why can't this be std::vector<IntList> (if IntList is valid,. we should be able to hold collections of them)

File: tools/autograd/templates/Functions.cpp [hunk 3]
```diff
@@ -364,17 +364,23 @@ Tensor unsqueeze_to(const Tensor & self, int64_t dim, IntList sizes) {
   return self;
 }
 
-std::vector<Tensor> cat_tensors_backward(const Tensor & grad, const std::vector<int64_t> &sizes, int64_t dim) {
+std::vector<Tensor> cat_tensors_backward(const Tensor & grad, const std::vector<std::vector<int64_t>> &sizes, int64_t dim) {
+  if (sizes.size() > 0) {
+    // cat wraps dim to the first tensor's shape 
+    dim = at::maybe_wrap_dim(dim, sizes[0].size());
```
Comment (gchanan) [inline tools/autograd/templates/Functions.cpp]: can we move this logic into wrap_dim_utils?  In another PR you change how TensorList wrap_dim works, but it will be hard to remember to update this.

File: tools/autograd/load_derivatives.py (hunk 2 above)
Comment (zou3519) [reply tools/autograd/load_derivatives.py]: I tried using `std::vector<IntList>` instead of `std::vector<std::vector<int64_t>>` and the values inside changes between the forward and backward passes (I'm not sure why)... In addition the ArrayRef source code https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/ArrayRef.h#L23-L33 comes with a warning to not use it for storage.

File: tools/autograd/templates/Functions.cpp (hunk 3 above)
Comment (zou3519) [reply tools/autograd/templates/Functions.cpp]: My intention was to delete this piece in #5837 after this PR gets merged in because it won't be necessary anymore. I can add it as a new function in wrap_dim_utils but it'll get deleted by #5837 anyways.

File: tools/autograd/templates/Functions.cpp (hunk 1 above)
Comment (zou3519) [reply tools/autograd/templates/Functions.cpp]: `shape == {0}` doesn't compile, should I try `shape == std::vector<int>({0})` instead?

File: tools/autograd/load_derivatives.py (hunk 2 above)
Comment (gchanan) [reply tools/autograd/load_derivatives.py]: The question still remains though, why is it okay to use IntList normally?  Is it transformed into a vector somewhere?

File: tools/autograd/templates/Functions.cpp (hunk 1 above)
Comment (gchanan) [reply tools/autograd/templates/Functions.cpp]: Ya the assumption was sizes[o] would be an IntList due to the above comment, in which case IntList({0}) should work.

File: tools/autograd/templates/Functions.cpp (hunk 3 above)
Comment (gchanan) [reply tools/autograd/templates/Functions.cpp]: I'm not sure I buy https://github.com/pytorch/pytorch/pull/5837 yet, can we make this as standalone as possible?

File: tools/autograd/load_derivatives.py (hunk 2 above)
Comment (zou3519) [reply tools/autograd/load_derivatives.py]: Yes, IntList is transformed to a std::vector<int64_t> by the code generation. I'm still trying to figure out where that happens

Comment (gchanan) [reply tools/autograd/load_derivatives.py]: here? https://github.com/pytorch/pytorch/blob/acc409396bda54e25dd0cccbd526821c52645662/tools/autograd/gen_autograd_functions.py#L139-L140.  Looks like you can just add another case here.

File: tools/autograd/templates/Functions.cpp (hunk 3 above)
Comment (zou3519) [reply tools/autograd/templates/Functions.cpp]: Sounds good!

File: tools/autograd/load_derivatives.py (hunk 2 above)
Comment (zou3519) [reply tools/autograd/load_derivatives.py]: I looked into it a bit more: IntList is transformed to a std::vector<int64_t> by the code generation, and one can pass in a std::vector<int64_t> into a function that takes IntList.

We don't have an analogous thing for std::vector<std::vector<int64_t>> (Unless each inner std::vector<int64_t> has the same size, but this isn't an assumption that we can make here).

The alternative to what I have now is using std::vector<IntList>. There are a few things that would need to happen to support this change:
1) Make the codegen translate `std::vector<IntList>` to `std::vector<std::vector<int64_t>>`
2) The cat_tensors_backward function will still take `std::vector<std::vector<int64_t>>`, unless we also want to change its argument to `std::vector<IntList>` for consistency. Then there needs to be an implicit conversion from `std::vector<std::vector<int64_t>>` to `std::vector<IntList>` which I'm not sure how to do.

Because of this, I think it's best to keep the usage of `std::vector<std::vector<int64_t>>` here to avoid the extra complexity -- what do you think?

Comment (gchanan) [reply tools/autograd/load_derivatives.py]: Sounds good to me, I don't think you can do the the implicit conversion.

File: tools/autograd/templates/Functions.cpp [hunk 4]
```diff
@@ -364,17 +364,20 @@ Tensor unsqueeze_to(const Tensor & self, int64_t dim, IntList sizes) {
   return self;
 }
 
-std::vector<Tensor> cat_tensors_backward(const Tensor & grad, const std::vector<int64_t> &sizes, int64_t dim) {
+std::vector<Tensor> cat_tensors_backward(const Tensor & grad, const std::vector<std::vector<int64_t>> &sizes, int64_t dim) {
```
Comment (ezyang) [inline tools/autograd/templates/Functions.cpp]: Hmmmmmmmm. You told me that this wasn't going to be part of the ATen API, which was true, but it's part of the "code in Functions.cpp which morally should be in ATen but isn't because shenanigans".

Last time this happened to me, I think I ended up passing the entire list of tensors to the function in question, because I secretly needed them anyway for something else. That's clearly not appropriate here. I guess this implies we should get something like `std::vector<TensorGeometry>` or something similar working in the codegen.
