### PR TITLE
Fix torch.diag backward with non-square matrix

### LINKED ISSUE #4299: log_softmax + torch.diag backward() error
Reported here: https://discuss.pytorch.org/t/torch-diag-of-a-non-square-matrix-backward-error/11426

MWE: (tested on master)
```
import torch
aa = torch.nn.functional.log_softmax(torch.autograd.Variable(torch.randn(4, 3), requires_grad=1), 1)                                   
b = torch.diag(aa, 1)
c = torch.sum(b)
c.backward()
>>>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rzou/pytorch/torch/autograd/variable.py", line 110, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/rzou/pytorch/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
RuntimeError: output and gradOutput shapes do not match: output [4 x 3], gradOutput [3 x 3] at /home/rzou/pytorch/aten/src/THNN/generic/
```

### PR DESCRIPTION
**Pull request by zou3519**
Fixes #4299 

Previously, the gradient of a non-square matrix input to `torch.diag` would be a square matrix. This fixes that.

### Test Plan
New unit test in test_autograd.  Also run the following and verify the size of `x.grad` is okay:
```
x = Variable(torch.randn(3, 5), requires_grad=True)
x.diag().sum().backward()
x.grad.size()  # assert this is (3, 5)
```

### CODE REVIEW

File: tools/autograd/templates/Functions.cpp [hunk 1]
```diff
@@ -408,6 +408,27 @@ Tensor smooth_l1_loss_double_backward_grad_output(const Tensor & grad, const Ten
...
+  // cat rows or cols to grad_input so that it matches self's shape.
+  auto length = grad_input.size(0);
+  auto self_nrows = self.size(0);
+  auto self_ncols = self.size(1);
+  if (self_nrows == length) {
+    auto extra_cols = grad_input.type().zeros({self_nrows, self_ncols - length});
+    return at::cat({grad_input, extra_cols}, 1);
+  }
+  auto extra_rows = grad_input.type().zeros({self_nrows - length, self_ncols});
+  return at::cat({grad_input, extra_rows});
```
Comment (apaszke) [inline tools/autograd/templates/Functions.cpp]: I think there's a faster way to fill a diagonal (`stride + 1` trick is the important part here):
```cpp
auto grad_input = self.type().zeros(self.sizes());
auto diag = grad_input.as_strided({diag_length}, {self.size(1) + 1});
diag.copy_(grad);
return grad_input;
```

File: tools/autograd/templates/Functions.cpp [hunk 2]
```diff
@@ -408,6 +408,27 @@ Tensor smooth_l1_loss_double_backward_grad_output(const Tensor & grad, const Ten
   return (r * grad).sum().view({1});
 }
 
+Tensor diag_backward(const Tensor & grad, const Tensor & self, int64_t diagonal) {
```
Comment (apaszke) [inline tools/autograd/templates/Functions.cpp]: We shouldn't keep `self` alive - its sizes would be sufficient and I'm pretty sure there is a way to make the codegen save only them

Comment (gchanan) [reply tools/autograd/templates/Functions.cpp]: specifying `self.sizes()` in the backward should work.

Comment (zou3519) [reply tools/autograd/templates/Functions.cpp]: Thanks! `self.sizes()` worked

File: tools/autograd/templates/Functions.cpp (hunk 1 above)
Comment (zou3519) [reply tools/autograd/templates/Functions.cpp]: Thanks! Didn't realize this was a thing / this trick is pretty cool.

File: tools/autograd/templates/Functions.cpp [hunk 3]
```diff
@@ -408,6 +408,38 @@ Tensor smooth_l1_loss_double_backward_grad_output(const Tensor & grad, const Ten
...
+
+Tensor diag_backward(const Tensor & grad, IntList input_sizes, int64_t diagonal) {
+  auto ndimension = input_sizes.size();
+  TORCH_ASSERT(ndimension == 1 || ndimension == 2);
+
+  if (ndimension == 1 || input_sizes[0] == input_sizes[1]) {
+    return grad.diag(diagonal);
+  }
+
+  // Input was a matrix but was not square
```
Comment (apaszke) [inline tools/autograd/templates/Functions.cpp]: That's not true, because `torch.diag` works in two modes. It can either select out a diagonal from a tensor, or, if given a 1d input, it will create a zero-filled square matrix, with the given diagonal. This case doesn't seem to be handled in here

Comment (zou3519) [reply tools/autograd/templates/Functions.cpp]: If the input is 1-dimensional, or the input is a square matrix, then it's handled by the above case with `return grad.diag(diagonal)`. If it's neither of those it falls through to this comment which takes care of the 2d and not-square case.

Comment (apaszke) [reply tools/autograd/templates/Functions.cpp]: Right, my bad...

File: tools/autograd/templates/Functions.cpp [hunk 4]
```diff
@@ -598,6 +598,38 @@ Tensor smooth_l1_loss_double_backward_grad_output(const Tensor & grad, const Ten
   return (r * grad).sum().view({1});
 }
 
+inline int64_t diag_size(int64_t height, int64_t width, int64_t diagonal) {
```
Comment (SsnL) [inline tools/autograd/templates/Functions.cpp]: static please

File: tools/autograd/templates/Functions.cpp [hunk 5]
```diff
@@ -598,6 +598,38 @@ Tensor smooth_l1_loss_double_backward_grad_output(const Tensor & grad, const Ten
...
+Tensor diag_backward(const Tensor & grad, IntList input_sizes, int64_t diagonal) {
+  auto ndimension = input_sizes.size();
+  TORCH_ASSERT(ndimension == 1 || ndimension == 2);
+
+  if (ndimension == 1 || input_sizes[0] == input_sizes[1]) {
+    return grad.diag(diagonal);
+  }
+
+  // Input was a matrix but was not square
+  auto grad_input = grad.type().zeros(input_sizes);
```
Comment (SsnL) [inline tools/autograd/templates/Functions.cpp]: nit: `at::zeros_like(input)`

Comment (zou3519) [reply tools/autograd/templates/Functions.cpp]: `input` wasn't passed into this function but `input_sizes` was so that's why it's using `input_sizes`

**Review by ssnl — APPROVED** [review]
LGTM
