### PR TITLE
Translate None to zeros for old-style autograd functions

### LINKED ISSUE #4198: RuntimeError: dim() called on undefined Tensor
Reported here in a different form: https://discuss.pytorch.org/t/runtimeerror-contiguous-is-not-implemented-for-type-undefinedtype/11124/30 .

Took me a while to isolate the bug but below is a script to reproduce this:
```
import torch
from torch.autograd import Variable
from torch.autograd import Function

class Fn(Function):
    def forward(self, x, y):
        return torch.zeros(2, 2, 2)

    def backward(self, grad_output):
        return torch.zeros(2, 2, 2), None

x = Variable(torch.zeros(1), requires_grad=True)
y = x[0].expand(2000, 5)
model = Fn()
model(x, y).sum().backward()
```
I'm looking into it.

### PR DESCRIPTION
**Pull request by zou3519**
Fixes #4198. This changes None elements of grad_input tuples to zeros in "old-style" autograd functions, to match "new-style" autograd function behavior.

I reused a function that changes grad_outputs to zeroes if any of them are None. I'm not sure if this function has other side effects that should only apply to grad_outputs only but it doesn't look like it does.

### Test Plan
New unit test in test_autograd

### CODE REVIEW

File: torch/csrc/autograd/python_function.cpp [hunk 1]
```diff
@@ -849,35 +849,35 @@ PyObject *THPFunction_apply(PyObject *cls, PyObject *inputs)
...
-  if (!grad_output) throw python_error();
+  THPObjectPtr grads;
+  grads = PyTuple_New(num_grads);
+  if (!grads) throw python_error();
 
   // Look for Nones and replace them with new buffers
-  auto& output_info = self->output_info;
-  for (int i = 0; i < num_grad_output; i++) {
-    PyObject *grad = PyTuple_GET_ITEM(raw_grad_output.get(), i);
+  auto& grads_info = is_grad_output ? self->output_info : self->input_info;
```
Comment (colesbury) [inline torch/csrc/autograd/python_function.cpp]: Can you add an assertion that `TORCH_ASSERT(grads_info.size() == (size_t)num_grads)`

**Review by colesbury — APPROVED** [review]
lgtm

**Review by apaszke — APPROVED** [review]
