### PR TITLE
Fix clang-802.0.42 tuple overload bug, fixes #3234.

### LINKED ISSUE #3234: OSX from Source ``error: call to 'recordTrace' is ambiguous``
```bash
torch/csrc/autograd/generated/VariableType.cpp:381:22: error: call to 'recordTrace' is ambiguous
      jit::Node *n = jit::tracer::recordTrace( "fill_", { self }, self );
                     ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/hangzhang/pytorch/torch/csrc/jit/tracer.h:262:14: note: candidate function
inline Node* recordTrace(std::string op, std::initializer_list<Variable> inputs, const Variable& output) {
             ^
/Users/hangzhang/pytorch/torch/csrc/jit/tracer.h:265:14: note: candidate function
inline Node* recordTrace(std::string op, std::initializer_list<Variable> inputs, const std::tuple<Variable, Variable>& outputs) {
             ^
/Users/hangzhang/pytorch/torch/csrc/jit/tracer.h:268:14: note: candidate function
inline Node* recordTrace(std::string op, std::initializer_list<Variable> inputs, const std::tuple<Variable, Variable, Variable>& outputs) {
             ^
/Users/hangzhang/pytorch/torch/csrc/jit/tracer.h:271:14: note: candidate function
inline Node* recordTrace(std::string op, at::TensorList inputs, const Variable& output) {
```
when executing:
```bash
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/usr/local/cuda/include -I/Users/hangzhang/pytorch -I/Users/hangzhang/pytorch/torch/csrc -I/Users/hangzhang/pytorch/torch/lib/pybind11/include -I/Users/hangzhang/pytorch/torch/lib/tmp_install/include -I/Users/hangzhang/pytorch/torch/lib/tmp_install/include/TH -I/Users/hangzhang/pytorch/torch/lib/tmp_install/include/THPP -I/Users/hangzhang/pytorch/torch/lib/tmp_install/include/THNN -I/Users/hangzhang/pytorch/torch/lib/tmp_install/include/ATen -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/Users/hangzhang/pytorch/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/Users/hangzhang/pytorch/torch/lib/tmp_install/include/THCUNN -I/anaconda/include/python3.6m -c torch/csrc/autograd/generated/python_nn_functions.cpp -o build/temp.macosx-10.7-x86_64-3.6/torch/csrc/autograd/generated/python_nn_functions.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
```

### PR DESCRIPTION
**Pull request by ezyang**
Originally, my plan for emit_record_trace was to keep it as
simple as possible, if at the expense of some somewhat ugly
overloads.  So this meant we had a 'recordTrace' function
with overloads like this:

  recordTrace(..., const Variable& out)
  recordTrace(..., const std::tuple<Variable, Variable>& out)

Unfortunately, this triggers a bug in clang-802.0.42
(widely used in macOS Sierra 10.12.6) wherein a Variable is
implicitly convertible into a std::tuple<Variable, Variable>;
a minimal repro can be seen below here:

  #include <tuple>
  struct T {};
  void f(const std::tuple<T, T>&) {}
  void g(T& x) { f(x); }

To work around this bug, the code generator is a bit more
complicated, and is taught how to handle this situation.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by apaszke** [comment]
Can you please also post before and after snippets of generated functions?

**Comment by ezyang** [comment]
Oops sorry.

```
Previously the generated code looked like:

  jit::tracer::recordTrace( "min", { self }, ret );

Now it looks like:

  jit::tracer::recordTrace( "min", { self }, { std::get<0>(ret), std::get<1>(ret) } );
                          
```

File: tools/autograd/templates/VariableType.cpp [hunk 1]
```diff
@@ -195,6 +195,13 @@ static VariableFlags compute_flags_tmpl(T tensors) {
 using TensorRef = std::reference_wrapper<const Tensor>;
 using TensorRefList = std::initializer_list<TensorRef>;
 
+// ArrayRef is not covariant, so we need to do some work to apply the
+// implicit constructor
```
Comment (apaszke) [inline tools/autograd/templates/VariableType.cpp]: What's an ArrayRef here? I can't see it. Is TensorList an alias to `ArrayRef<at::Tensor>`?

File: tools/autograd/templates/VariableType.cpp [hunk 2]
```diff
@@ -195,6 +195,13 @@ static VariableFlags compute_flags_tmpl(T tensors) {
...
+static variable_list castTensorList(const TensorList& tensors) {
```
Comment (apaszke) [inline tools/autograd/templates/VariableType.cpp]: can you keep the underscore convention for names?

File: tools/autograd/templates/VariableType.cpp (hunk 1 above)
Comment (ezyang) [reply tools/autograd/templates/VariableType.cpp]: ArrayRef is defined in ATen, and it's a sort of general "reference to array-like thing". TensorList is indeed that alias.

Comment (apaszke) [reply tools/autograd/templates/VariableType.cpp]: Yeah I know what an `ArrayRef` is, but I admit my comment wasn't clear. I meant that the comment is confusing for readers that have little ATen experience, because there's no clear connection to the surrounding code. Change ArrayRef to TensorList

Comment (ezyang) [reply tools/autograd/templates/VariableType.cpp]: But you can only speak of the covariance of a type constructor (ArrayRef) not a type (TensorList). What I'll do is mention the alias.

Comment (apaszke) [reply tools/autograd/templates/VariableType.cpp]: That's fine with me. Just do something to make it clear that the comment actually applies to this code

Comment (apaszke) [reply tools/autograd/templates/VariableType.cpp]: To be honest I didn't remember for sure if `TensorList` was a vector like `variable_list` or if it was an `ArrayRef`

**Review by apaszke — APPROVED** [review]

File: tools/autograd/gen_variable_type.py [hunk 3]
```diff
@@ -599,7 +599,41 @@ def emit_buffers(buffers):
         return res
 
     def emit_record_trace(env, declaration):
+
+        # Note [clang-802.0.42 tuple overload bug]
```
Comment (colesbury) [inline tools/autograd/gen_variable_type.py]: I don't see this note as being very useful for any reading the code. It's all about the previous implementation, which you don't see. The new implementation is simple and makes sense. There are a very large number of alternative implementations that may be reasonable, and we don't explain the decision for not using each of them.

This seems more appropriate in the commit message.

Comment (ezyang) [reply tools/autograd/gen_variable_type.py]: Well, it's in the commit message, so we can always delete this note later :)
