### PR TITLE
Fix reduction functions to respect the stride of the output

### LINKED ISSUE #4974: torch.sum() ignores stride in out tensor
The `torch.sum()` function writes its outputs in erroneous locations when the out `kwarg` is used. Repro:

```python
import torch

i = 1
a = torch.zeros(5, 3)
b = torch.randn(3, 5)

ac = a.clone()
ac[:, i].copy_(b.sum(0))
print(ac)

ac = a.clone()
b.sum(0, out=ac[:, i])
print(ac)
```

Output:
```bash
lvdmaaten-mbp:Desktop lvdmaaten$ python bug.py
0.0000 -0.1515 0.0000
0.0000 1.8761 0.0000
0.0000 -1.7563 0.0000
0.0000 0.5194 0.0000
0.0000 1.5322 0.0000
[torch.FloatTensor of size 5x3]
0.0000 -0.1515 1.8761
-1.7563 0.5194 1.5322
0.0000 0.0000 0.0000
0.0000 0.0000 0.0000
0.0000 0.0000 0.0000
[torch.FloatTensor of size 5x3]
```

I presume what happens is that `torch.sum()` does not respect the stride of `a[:, i]` when putting outputs in place.

Tested on PyTorch version 0.3.0.post4.

### PR DESCRIPTION
**Pull request by zou3519**
Fixes #4974 

Consider reduction ops like `torch.sum`, `torch.prod`, etc, of the form
`reduce_op(output, input, keepdim)`

Let `output_size` be the size of the output with `keepdim=False`, and `output_keepdim_size` be the size of the output with `keepdim=True`.

Right now, what happens in a reduce op is the following:
we have an `input` and an `output`. `output` is always resized to `output_keepdim_size`. Then, the reduction op is performed with that size, and output is finally either squeezed to `output_size` or kept at `output_keepdim_size` depending on what `keepdim` is.

The problem with what currently happens is that if `keepdim=False`and `output` initially has size `output_size` then `output` will be resized to `output_keepdim_size`, the reduce op will be performed, and then output will be squeezed to `output_size`. This resize is not a no-op and will affect `output`'s contiguity. 

This PR fixes the issue by always unsqueezing `output` to `output_keepdim_size`. This operation preserves `output`'s contiguity.

This fixes the following operations:
- mean
- median
- mode
- norm
- prod
- sum
- std
- var
- max
- min

### Test Plan
New unit tests

### CODE REVIEW

File: aten/src/TH/generic/THTensorMath.c [hunk 1]
```diff
@@ -2226,13 +2226,33 @@ ptrdiff_t THTensor_(numel)(THTensor *t)
...
+
 void THTensor_(max)(THTensor *values_, THLongTensor *indices_, THTensor *t, int dimension, int keepdim)
 {
   THLongStorage *dim;
 
   THArgCheck(dimension >= 0 && dimension < THTensor_(nDimension)(t), 2, "dimension %d out of range",
       dimension + TH_INDEX_BASE);
 
+  int in_dims = THTensor_(nDimension)(t);
+  THTensor_(preserveReduceDimSemantics)(values_, in_dims, dimension, keepdim);
```
Comment (soumith) [inline aten/src/TH/generic/THTensorMath.c]: if you unsqueezed r_ here (i.e. if keepdim = False), dont you have to squeeze it before returning?

Comment (zou3519) [reply aten/src/TH/generic/THTensorMath.c]: In all the functions that have `keepdim`, there's a `squeeze` before returning if `keepdim=False`. Example: https://github.com/zou3519/pytorch/blob/5c21080bbed5ff706c6b022073021c78265641ff/aten/src/TH/generic/THTensorMath.c#L2490
