### PR TITLE
Fix segfault in autograd:

### LINKED ISSUE #1622: Segfault when using torch.autograd.grad
I've been trying to implement Improved Wasserstein GANs, which requires `torch.autograd.grad` from the bleeding-edge repo, but I've been getting segfaults. Here's a minimum working example:

```
import torch
from torch.autograd import Variable

x = Variable(torch.ones(1))
y = x**2
grad = torch.autograd.grad(x,y)
```

Obviously this is a nonsense thing to do but it shouldn't segfault, and I presume it's related to my issues (which are definitely `torch.autograd.grad` related). I'm on the HEAD commit (45524e), I'm running in a conda env having followed the install from source instructions, and I'm using Fedora 25.

Here is the output when I run valgrind:

```
valgrind --track-origins=yes -- ipython segfault.py

...

==28387== Conditional jump or move depends on uninitialised value(s)
==28387==    at 0x4ED16DC: PyObject_Free (obmalloc.c:1013)
==28387==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==28387==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==28387==    by 0x4F4D33C: load_source_module (import.c:1122)
==28387==    by 0x4F4E0D0: import_submodule (import.c:2725)
==28387==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==28387==    by 0x4F4EAF3: import_module_level (import.c:2293)
==28387==    by 0x4F4EAF3: PyImport_ImportModuleLevel (import.c:2312)
==28387==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==28387==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==28387==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==28387==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==  Uninitialised value was created by a heap allocation
==28387==    at 0x4C2DB9D: malloc (vg_replace_malloc.c:299)
==28387==    by 0x4F4D120: load_source_module (import.c:1086)
==28387==    by 0x4F4E0D0: import_submodule (import.c:2725)
==28387==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==28387==    by 0x4F4EAF3: import_module_level (import.c:2293)
==28387==    by 0x4F4EAF3: PyImport_ImportModuleLevel (import.c:2312)
==28387==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==28387==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==28387==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==28387==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==28387==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==28387== 
==28387== Conditional jump or move depends on uninitialised value(s)
==28387==    at 0x3674D08F: __intel_sse2_strrchr (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x366EB411: _INTERNAL_45_______src_thirdparty_tbb_omp_dynamic_link_cpp_7b148ce4::__kmp::init_dl_data() (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x366EB366: __sti__$E (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x3675DF25: ??? (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x3665D48A: ??? (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x2: ???
==28387==    by 0x40109F9: call_init.part.0 (in /usr/lib64/ld-2.24.so)
==28387==    by 0x4010B4A: _dl_init (in /usr/lib64/ld-2.24.so)
==28387==    by 0x4015AA5: dl_open_worker (in /usr/lib64/ld-2.24.so)
==28387==    by 0x40108E3: _dl_catch_error (in /usr/lib64/ld-2.24.so)
==28387==    by 0x4015078: _dl_open (in /usr/lib64/ld-2.24.so)
==28387==    by 0x5454F08: dlopen_doit (in /usr/lib64/libdl-2.24.so)
==28387== 
==28387== Invalid read of size 4
==28387==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==28387==    by 0x2B22D32E: THPPointer<_object>::free() (object_ptr.cpp:8)
==28387==    by 0x2B1D9DAF: THPPointer<_object>::~THPPointer() (object_ptr.h:12)
==28387==    by 0x2B1D9AA1: THPUtils_unpackString(_object*) (python_strings.h:32)
==28387==    by 0x2B1D8836: THPModule_addDocStr(_object*, _object*) (Module.cpp:443)
==28387==    by 0x4F371E4: call_function (ceval.c:4352)
==28387==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==28387==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==28387==    by 0x4F4D31D: load_source_module (import.c:1121)
==28387==    by 0x4F4E0D0: import_submodule (import.c:2725)
==28387==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==28387==  Address 0x5f2d020 is 6,144 bytes inside a block of size 6,453 free'd
==28387==    at 0x4C2FC47: realloc (vg_replace_malloc.c:785)
==28387==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==28387==    by 0x4EFD593: PyUnicodeUCS4_EncodeUTF8 (unicodeobject.c:2238)
==28387==    by 0x2B1D99AD: THPUtils_unpackString(_object*) (python_strings.h:27)
==28387==    by 0x2B1D8836: THPModule_addDocStr(_object*, _object*) (Module.cpp:443)
==28387==    by 0x4F371E4: call_function (ceval.c:4352)
==28387==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==28387==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==28387==    by 0x4F4D31D: load_source_module (import.c:1121)
==28387==    by 0x4F4E0D0: import_submodule (import.c:2725)
==28387==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==28387==  Block was alloc'd at
==28387==    at 0x4C2DB9D: malloc (vg_replace_malloc.c:299)
==28387==    by 0x4ED9A79: PyString_FromStringAndSize (stringobject.c:88)
==28387==    by 0x4EFD5BD: PyUnicodeUCS4_EncodeUTF8 (unicodeobject.c:2181)
==28387==    by 0x2B1D99AD: THPUtils_unpackString(_object*) (python_strings.h:27)
==28387==    by 0x2B1D8836: THPModule_addDocStr(_object*, _object*) (Module.cpp:443)
==28387==    by 0x4F371E4: call_function (ceval.c:4352)
==28387==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==28387==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==28387==    by 0x4F4D31D: load_source_module (import.c:1121)
==28387==    by 0x4F4E0D0: import_submodule (import.c:2725)
==28387==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==28387== 
==28387== Syscall param sched_setaffinity(mask) points to unaddressable byte(s)
==28387==    at 0x5C65BF9: syscall (in /usr/lib64/libc-2.24.so)
==28387==    by 0x366F7028: __kmp_affinity_determine_capable (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x366D7A24: __kmp_env_initialize(char const*) (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x366C3E06: _INTERNAL_23_______src_kmp_runtime_c_680c9f7a::__kmp_do_serial_initialize() (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x366B8F84: __kmp_get_global_thread_id_reg (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x366AF846: GOMP_parallel_start@@VERSION (in /home/phil/anaconda2/envs/pytorch/lib/libiomp5.so)
==28387==    by 0x2C9FCF50: THFloatTensor_fill (THTensorMath.c:102)
==28387==    by 0x2CA2E3A8: THFloatTensor_ones (THTensorMath.c:1862)
==28387==    by 0x2B404FF3: THPFloatTensor_stateless_ones(_object*, _object*, _object*) (TensorMethods.cpp:369)
==28387==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==28387==    by 0x2B21FCC0: THPUtils_dispatchStateless(_object*, char const*, _object*, _object*) (utils.cpp:154)
==28387==    by 0x2B1D4F70: THPModule_ones(_object*, _object*, _object*) (Module.cpp:282)
==28387==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==28387== 
==28387== Invalid read of size 8
==28387==    at 0x2B23C8F0: __gnu_cxx::__normal_iterator<std::pair<std::shared_ptr<torch::autograd::Function>, int>*, std::vector<std::pair<std::shared_ptr<torch::autograd::Function>, int>, std::allocator<std::pair<std::shared_ptr<torch::autograd::Function>, int> > > >::__normal_iterator(std::pair<std::shared_ptr<torch::autograd::Function>, int>* const&) (stl_iterator.h:726)
==28387==    by 0x2B23AB54: std::vector<std::pair<std::shared_ptr<torch::autograd::Function>, int>, std::allocator<std::pair<std::shared_ptr<torch::autograd::Function>, int> > >::begin() (stl_vector.h:539)
==28387==    by 0x2B26944B: compute_partial_exec_callbacks(std::vector<std::pair<std::shared_ptr<torch::autograd::Function>, int>, std::allocator<std::pair<std::shared_ptr<torch::autograd::Function>, int> > > const&, CallbackContext const&, std::unordered_map<torch::autograd::Function*, std::function<bool (torch::autograd::Function*, std::vector<std::shared_ptr<torch::autograd::Variable>, std::allocator<std::shared_ptr<torch::autograd::Variable> > >&)>, std::hash<torch::autograd::Function*>, std::equal_to<torch::autograd::Function*>, std::allocator<std::pair<torch::autograd::Function* const, std::function<bool (torch::autograd::Function*, std::vector<std::shared_ptr<torch::autograd::Variable>, std::allocator<std::shared_ptr<torch::autograd::Variable> > >&)> > > >&) (python_engine.cpp:72)
==28387==    by 0x2B26A456: THPEngine_run_backward(THPEngine*, _object*, _object*) (python_engine.cpp:195)
==28387==    by 0x4F371E4: call_function (ceval.c:4352)
==28387==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F381F6: fast_function (ceval.c:4447)
==28387==    by 0x4F381F6: call_function (ceval.c:4372)
==28387==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==28387==    by 0x4F37807: exec_statement (ceval.c:5050)
==28387==    by 0x4F37807: PyEval_EvalFrameEx (ceval.c:2106)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F381F6: fast_function (ceval.c:4447)
==28387==    by 0x4F381F6: call_function (ceval.c:4372)
==28387==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==28387==  Address 0x10 is not stack'd, malloc'd or (recently) free'd
==28387== 
==28387== 
==28387== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==28387==  Access not within mapped region at address 0x10
==28387==    at 0x2B23C8F0: __gnu_cxx::__normal_iterator<std::pair<std::shared_ptr<torch::autograd::Function>, int>*, std::vector<std::pair<std::shared_ptr<torch::autograd::Function>, int>, std::allocator<std::pair<std::shared_ptr<torch::autograd::Function>, int> > > >::__normal_iterator(std::pair<std::shared_ptr<torch::autograd::Function>, int>* const&) (stl_iterator.h:726)
==28387==    by 0x2B23AB54: std::vector<std::pair<std::shared_ptr<torch::autograd::Function>, int>, std::allocator<std::pair<std::shared_ptr<torch::autograd::Function>, int> > >::begin() (stl_vector.h:539)
==28387==    by 0x2B26944B: compute_partial_exec_callbacks(std::vector<std::pair<std::shared_ptr<torch::autograd::Function>, int>, std::allocator<std::pair<std::shared_ptr<torch::autograd::Function>, int> > > const&, CallbackContext const&, std::unordered_map<torch::autograd::Function*, std::function<bool (torch::autograd::Function*, std::vector<std::shared_ptr<torch::autograd::Variable>, std::allocator<std::shared_ptr<torch::autograd::Variable> > >&)>, std::hash<torch::autograd::Function*>, std::equal_to<torch::autograd::Function*>, std::allocator<std::pair<torch::autograd::Function* const, std::function<bool (torch::autograd::Function*, std::vector<std::shared_ptr<torch::autograd::Variable>, std::allocator<std::shared_ptr<torch::autograd::Variable> > >&)> > > >&) (python_engine.cpp:72)
==28387==    by 0x2B26A456: THPEngine_run_backward(THPEngine*, _object*, _object*) (python_engine.cpp:195)
==28387==    by 0x4F371E4: call_function (ceval.c:4352)
==28387==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F381F6: fast_function (ceval.c:4447)
==28387==    by 0x4F381F6: call_function (ceval.c:4372)
==28387==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==28387==    by 0x4F37807: exec_statement (ceval.c:5050)
==28387==    by 0x4F37807: PyEval_EvalFrameEx (ceval.c:2106)
==28387==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==28387==    by 0x4F381F6: fast_function (ceval.c:4447)
==28387==    by 0x4F381F6: call_function (ceval.c:4372)
==28387==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==28387==  If you believe this happened as a result of a stack
==28387==  overflow in your program's main thread (unlikely but
==28387==  possible), you can try to increase the size of the
==28387==  main thread stack using the --main-stacksize= flag.
==28387==  The main thread stack size used in this run was 8388608.
==28387== 
==28387== HEAP SUMMARY:
==28387==     in use at exit: 21,966,492 bytes in 66,340 blocks
==28387==   total heap usage: 281,301 allocs, 214,961 frees, 163,888,150 bytes allocated
==28387== 
==28387== LEAK SUMMARY:
==28387==    definitely lost: 0 bytes in 0 blocks
==28387==    indirectly lost: 0 bytes in 0 blocks
==28387==      possibly lost: 409,732 bytes in 477 blocks
==28387==    still reachable: 21,556,760 bytes in 65,863 blocks
==28387==                       of which reachable via heuristic:
==28387==                         stdstring          : 134,540 bytes in 362 blocks
==28387==                         length64           : 599,664 bytes in 192 blocks
==28387==         suppressed: 0 bytes in 0 blocks
==28387== Rerun with --leak-check=full to see details of leaked memory
==28387== 
==28387== For counts of detected and suppressed errors, rerun with: -v
==28387== ERROR SUMMARY: 3644 errors from 125 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

Any ideas?

### PR DESCRIPTION
**Pull request by colesbury**
1) Every "output" variable must have a grad_fn or grad_accumulator
2) compute_partial_exec_callbacks uses Python errors

Fixes #1622

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
2.7 is failing:

```
20:23:34   File "test_autograd.py", line 250, in test_grad_badcalls
20:23:34     with self.assertRaisesRegex(RuntimeError, 'does not require grad'):
20:23:34 AttributeError: 'TestAutograd' object has no attribute 'assertRaisesRegex'
```

File: torch/csrc/autograd/python_engine.cpp [hunk 1]
```diff
@@ -191,7 +193,9 @@ PyObject *THPEngine_run_backward(THPEngine *self, PyObject *args, PyObject *kwar
     }
     // Disable execution for all unneeded functions
     if (only_inputs) {
-      compute_partial_exec_callbacks(roots, ctx, callbacks);
+      if (!compute_partial_exec_callbacks(roots, ctx, callbacks)) {
```
Comment (apaszke) [inline torch/csrc/autograd/python_engine.cpp]: What was wrong with raising an error here?

Comment (colesbury) [inline torch/csrc/autograd/python_engine.cpp]: There's no try/catch context (so it aborts)

Comment (apaszke) [inline torch/csrc/autograd/python_engine.cpp]: Can't we just wrap the engine's function in `HANDLE_TH_ERRORS`? It should be there anyway and it's a clearer way of handling errors

Comment (colesbury) [inline torch/csrc/autograd/python_engine.cpp]: Sure

**Review by apaszke — APPROVED** [review]
