### PR TITLE
Better error messages for Aten tensor types

### LINKED ISSUE #2138: RuntimeError: expected Double tensor (got Float tensor)
```python

  # -*- coding: utf-8 -*-
  from __future__ import absolute_import
  import numpy as np
  import torch
  import torch.nn as nn
  from torch.autograd import Variable
    
    
  kernel = torch.from_numpy(np.random.random_sample((1, 3))).double()
  input_ = torch.from_numpy(np.random.random_sample((1, 1, 1, 6))).double()
                                                                                                           
  print(kernel)
  print(input_)
   
  model = nn.Sequential(nn.Conv2d(1, 1, (1, 3), stride=1, padding=0, bias=False))
  model[0].weight.data.copy_(kernel)
  A = Variable(input_)
  out = model(A)
  print(out.data)
```
But the input is actually DoubleTensor
```
$ python test.py

 0.0100  0.6528  0.8658
[torch.DoubleTensor of size 1x3]


(0 ,0 ,.,.) = 
  0.9582  0.9593  0.1207  0.5719  0.3984  0.4603
[torch.DoubleTensor of size 1x1x1x6]

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    out = model(A)
  File "/home/diggerdu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/diggerdu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 64, in forward
    input = module(input)
  File "/home/diggerdu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/diggerdu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/diggerdu/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 40, in conv2d
    return f(input, weight, bias)
RuntimeError: expected Double tensor (got Float tensor)

```

### PR DESCRIPTION
**Pull request by zou3519**
Fixes #2138.

Right now if an type error occurs between tensors in the Aten backend an error message like the following is thrown:
`RuntimeError: Expected object of type CPUDoubleType but found type CPUFloatType for argument #3 'weight'`

This could be confusing for people who only use pytorch and don't know about Aten. This pr adds a a find & replace for those type names when error messages that are propagated to the python interpreter contain them.

### Test Plan
Run something that causes a type error and check the error message. Running the script in #2138 now gives the output
image

### CODE REVIEW

File: torch/csrc/Exceptions.cpp [hunk 1]
```diff
@@ -11,3 +13,58 @@ bool THPException_init(PyObject *module)
...
+    {"CPULongType", "torch.LongTensor"},
+    {"CPUShortType", "torch.ShortTensor"},
+    {"CPUHalfType", "torch.HalfTensor"},
+  };
+
+  for (const auto & it : changes) {
+    replaceAll(str, it.first, it.second);
+  }
+
+  return str.c_str();
```
Comment (colesbury) [inline torch/csrc/Exceptions.cpp]: This isn't safe -- the c_str() lifetime is only as long as the owning std::string. The function should return a std::string instead.

**Review by soumith — APPROVED** [review]

File: torch/csrc/Exceptions.h [hunk 2]
```diff
@@ -14,7 +14,7 @@
   } catch (python_error &e) {                                                  \
     return retval;                                                             \
   } catch (std::exception &e) {                                                \
-    PyErr_SetString(PyExc_RuntimeError, e.what());                             \
+    PyErr_SetString(PyExc_RuntimeError, processErrorMsg(e.what()));            \
```
Comment (colesbury) [inline torch/csrc/Exceptions.h]: Note that both of the following would be safe if processErrorMsg returns a `std::string`:

```c++
auto msg = processErrorMsg(e.what());
PyErr_SetString(PyExc_RuntimeError, msg.c_str());
```

This is safe because PyErr_SetString makes a copy of the `const char *`


```c++
PyErr_SetString(PyExc_RuntimeError, processErrorMsg(e.what()).c_str());
```

This is still safe because temporaries (the return value of processErrorMsg) last the lifetime of the **full-expression** that contains the point where they're created.

File: torch/csrc/Exceptions.h [hunk 3]
```diff
@@ -68,4 +68,6 @@ struct python_error : public std::exception {
 bool THPException_init(PyObject *module);
 #endif
 
+const char * processErrorMsg(std::string str);
```
Comment (colesbury) [inline torch/csrc/Exceptions.h]: Put this in a `namespace torch` or prefix it with `THPException_`. (Namespaces are preferable).

**Review by colesbury — COMMENTED** [review]
Can you add a test to test_torch.py? You can use `assertRaisesRegex`

File: torch/csrc/Exceptions.h (hunk 2 above)
Comment (zou3519) [reply torch/csrc/Exceptions.h]: Thanks for the explanation!
