### PR TITLE
[ONNX] Support tensorList when Infers shape and type uninitialized output

### LINKED ISSUE #59179: ONNX export: RuntimeError: rINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen/core/jit_type_base.h":172
## 🐛 Bug

I'm trying to export Mozilla TTS Tacotron2 model into ONNX using TorchScript.

Here is my current progress: https://github.com/lasa01/TTS/tree/onnx.

Here is the export script: https://github.com/lasa01/TTS/blob/onnx/TTS/bin/convert_tacotron2_torch_to_onnx.py.

However, the export fails with the following error:

```
python -m TTS.bin.convert_tacotron2_torch_to_onnx.py --config_path ".\TTS\tts\configs\config.json" --output_path ".\data\converted_models\tts_model.onnx"
Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'outputs.17'. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'stop_tokens.15'. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'alignments.15'. This changes graph semantics.
D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\symbolic_opset9.py:2119: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  "or define the initial states (h0/c0) as inputs of the model. ")
D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\symbolic_opset11.py:573: UserWarning: This model contains a squeeze operation on dimension 1. The size of this dimension in the given input is 560. The model will be exported without the squeeze node. If the model is intended to be used with dynamic input shapes, please export with dynamic_axes argument.
  "input shapes, please export with dynamic_axes argument.")
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\lasa\Code\TTS\TTS\bin\convert_tacotron2_torch_to_onnx.py", line 102, in <module>
    verbose=True,
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 693, in _export
    dynamic_axes=dynamic_axes)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 465, in _model_to_graph
    module=module)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 1087, in _run_symbolic_function
    is_sub_block)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 1087, in _run_symbolic_function
    is_sub_block)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 1088, in _run_symbolic_function
    new_op_outputs = torch._C._jit_pass_fixup_onnx_controlflow_node(new_node, opset_version)
RuntimeError: rINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen/core/jit_type_base.h":172, please report a bug to PyTorch.
```

## To Reproduce

1. Clone https://github.com/lasa01/TTS/tree/onnx
1. Install dependencies.
1. Run `python -m TTS.bin.convert_tacotron2_torch_to_onnx.py --config_path "./TTS/tts/configs/config.json" --output_path "./data/converted_models/tts_model.onnx"`

## Expected behavior

The export succeeds.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0.dev20210529+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: 12.0.0
CMake version: version 3.18.4
Libc version: N/A

Python version: 3.6 (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.9.0.dev20210529+cu102
[pip3] torchaudio==0.9.0.dev20210529
[pip3] torchvision==0.11.0.dev20210529
[conda] Could not collect
```

Same issue also happened with PyTorch 1.8.1.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity @gmagogsfm

### PR DESCRIPTION
**Pull request by hwangdeyu**
Fixes #59179

Error message:
>ONNX export: RuntimeError: rINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen/core/jit_type_base.h":172

Cause tensor list is not support when Infers shape and type uninitialized output, so add it.

### CODE REVIEW

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 1]
```diff
@@ -258,25 +259,41 @@ bool IsUninitializedNode(Node* n) {
...
-  if (output_type->sizes().concrete_sizes().has_value()) {
-    auto size = output_type->sizes().concrete_sizes().value();
-    const_node->t_(attr::value, at::zeros(size, elem_type));
-    const_node->output()->setType(other_output->type());
-    const_node->output()->copyMetadata(other_output);
-  } else {
-    const_node->t_(attr::value, at::zeros({}, elem_type));
-    const_node->output()->setType(
-        TensorType::create(*(output_type->scalarType()), at::kCPU, {}, {}));
+  Node* const_node;
```
Comment (BowenBao) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:269]: Try to avoid uninitialized variable.

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 2]
```diff
@@ -258,25 +259,41 @@ bool IsUninitializedNode(Node* n) {
...
+  if (other_output->type()->cast<TensorType>() != nullptr) {
```
Comment (BowenBao) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:270]:
```suggestion
  if (auto other_type = other_output->type()->cast<TensorType>()) {
```

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 3]
```diff
@@ -258,25 +259,41 @@ bool IsUninitializedNode(Node* n) {
...
+    if (output_type->sizes().concrete_sizes().has_value()) {
+      auto size = output_type->sizes().concrete_sizes().value();
+      const_node->t_(attr::value, at::zeros(size, elem_type));
+      const_node->output()->setType(other_output->type());
+    } else {
+      const_node->t_(attr::value, at::zeros({}, elem_type));
+      const_node->output()->setType(
+          TensorType::create(*(output_type->scalarType()), at::kCPU, {}, {}));
+    }
+  } else if (other_output->type()->cast<ListType>() != nullptr) {
```
Comment (BowenBao) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:285]:
```suggestion
  } else if (auto output_type = other_output->type()->cast<ListType>()) {
```

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 4]
```diff
@@ -258,25 +259,41 @@ bool IsUninitializedNode(Node* n) {
...
+    auto output_type = other_output->type()->expect<ListType>();
+    TypePtr elem = output_type->getElementType();
+    const_node = graph->create(::c10::onnx::SequenceEmpty, 1);
+    if (elem->cast<TensorType>()->scalarType().has_value()) {
```
Comment (BowenBao) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:289]: condition need to check that `elem->cast<TensorType>()` is not nullptr

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 5]
```diff
@@ -258,25 +259,41 @@ bool IsUninitializedNode(Node* n) {
...
+      auto scalar_type = elem->cast<TensorType>()->scalarType().value();
+      auto onnx_type = ATenTypeToOnnxType(scalar_type);
+      const_node->i_(attr::dtype, onnx_type);
+      const_node->output()->setType(ListType::create(elem->cast<TensorType>()));
```
Comment (BowenBao) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:293]: this will copy over tensor shape from elem as well. is this intended?

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 6]
```diff
@@ -258,25 +259,41 @@ bool IsUninitializedNode(Node* n) {
...
+    } else {
+      const_node->output()->setType(other_output->type());
```
Comment (BowenBao) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:295]: so no scalar type to copy over from. this could be a problem, any thoughts on what we can do in general?

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp (hunk 1 above)
Comment (hwangdeyu) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:269]: Thanks, initialize it to nullptr.

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp (hunk 5 above)
Comment (hwangdeyu) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:291]: I thought that we copy over tensor shape from elem. I'm not particularly sure if that makes sense.
Is that more reasonable to use `setType(other_output->type())`?

Comment (BowenBao) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:292]: The current code is the same as `setType(other_output->type())`. `type` contains both `shape` and `scalarType`. If you intend to copy over both, then use `setType`, if you want to only copy `scalarType`, then you will need to update L#292

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 7]
```diff
@@ -258,25 +259,41 @@ bool IsUninitializedNode(Node* n) {
...
+      auto size = output_type->sizes().concrete_sizes().value();
+      const_node->t_(attr::value, at::zeros(size, elem_type));
+      const_node->output()->setType(other_output->type());
+    } else {
+      const_node->t_(attr::value, at::zeros({}, elem_type));
+      const_node->output()->setType(
+          TensorType::create(*(output_type->scalarType()), at::kCPU, {}, {}));
+    }
+  } else if (auto output_type = other_output->type()->cast<ListType>()) {
+    TypePtr elem = output_type->getElementType();
```
Comment (jiafatom) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:285]: For ListType case, I wonder what is the shape inference result look like. I am converting a silero model which uses this technique, looks like it returns Tensor[] but there is no shape for this Tensor[]. Seems that we need have a shape inference for each element in Tensor[].

File: test/onnx/test_pytorch_onnx_onnxruntime.py [hunk 8]
```diff
@@ -6262,6 +6262,52 @@ def forward(self, y):
...
+    @skipIfONNXShapeInference(False)
+    def test_uninitialized_tensorList_dynamic(self):
+        class UninitializedModel(torch.nn.Module):
+            def forward(self, y):
+                if y.shape[1] < 5:
+                    if y.size(0) == 1:
+                        y = y + 4
+                    else:
+                        return [y]
+                return [y]
```
Comment (jiafatom) [inline test/onnx/test_pytorch_onnx_onnxruntime.py:6290]: Can we have a unit test, if branch returns tensor list of empty list, else branch returns tensor list of several elements?

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 9]
```diff
@@ -258,25 +259,41 @@ bool IsUninitializedNode(Node* n) {
...
+    const_node = graph->create(::c10::onnx::SequenceEmpty, 1);
```
Comment (jiafatom) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:286]: Where is the code you add Identity node? Once you insert a new node to graph, you may need add shape inference for that node. See https://github.com/pytorch/pytorch/blob/dec5aa2260cef540b622bd9a9504b6f11cb1f607/torch/csrc/jit/passes/onnx.cpp#L286

Comment (hwangdeyu) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:286]: thanks David！
I'm not sure if SequenceEmpty needs an certain shape, will check in ONNX spec and try to use this function.

Comment (hwangdeyu) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:286]: btw, add Identity node in thins link [fixup_onnx_controlflow.cpp#L190]. We only deal with the TensorList case when Infer Shape and Type For UninitializedOutput.(https://github.com/pytorch/pytorch/blob/e523674c51072036a69125f098eb16c93f32b59c/torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp#L190)

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 10]
```diff
@@ -258,25 +259,43 @@ bool IsUninitializedNode(Node* n) {
...
+    if (elem->cast<TensorType>() &&
+        elem->cast<TensorType>()->scalarType().has_value()) {
+      auto scalar_type = elem->cast<TensorType>()->scalarType().value();
+      auto onnx_type = ATenTypeToOnnxType(scalar_type);
+      const_node->i_(attr::dtype, onnx_type);
+      const_node->output()->setType(other_output->type());
+    } else {
```
Comment (neginraoof) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:293]: I think we can also handle scalar type lists like (int[], float[], etc.) here.
Maybe like:
else if (elem->cast<IntType>()) {
      auto scalar_type = at::kLong;
      auto onnx_type = ATenTypeToOnnxType(scalar_type);
      const_node->i_(attr::dtype, onnx_type);
      const_node->output()->setType(other_output->type());
}

Comment (hwangdeyu) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:293]: Good point! Will add this part and tests.
By the way, Do you think we also need to add scalar type like(int, float etc..) in output_type?
https://github.com/pytorch/pytorch/blob/c3eb80300af37aa41b9e7ff2d3ff2220393db6b7/torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp#L284

Comment (hwangdeyu) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:291]: It seems the ONNX node type must be Tensor type. Even we return like the `intList`, it will also return the element tensor type. So we may not need to handle those type.
I have added this in test case.

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 11]
```diff
@@ -256,25 +257,43 @@ bool IsUninitializedNode(Node* n) {
 
 // Infer shape and type of the uninitialized_output from the corresponding
 // output of the other subblock. prim::Uninitialized node is proven to be
-// unused. So replace this node with a constant of the inferred shape and type.
+// unused. So replace this node with a constant(TensorType) or
+// Sequence(ListType) of the inferred shape and type.
```
Comment (jiafatom) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:261]: nit: add space

File: test/onnx/test_pytorch_onnx_onnxruntime.py [hunk 12]
```diff
@@ -6387,6 +6387,92 @@ def forward(self, y):
                       input_names=["input_1"],
                       dynamic_axes={"input_1": [0, 1]})
 
+    # ONNX::identity of sequence supported for ONNX opset >= 14
```
[the remark this answers is not in the document]
Comment (hwangdeyu) [reply test/onnx/test_pytorch_onnx_onnxruntime.py]: Thanks, using onnx::Identity makes it more precise.

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp (hunk 6 above)
Comment (neginraoof) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:295]: @hwangdeyu Is this comment addressed?

File: test/onnx/test_pytorch_onnx_onnxruntime.py [hunk 13]
```diff
@@ -6518,6 +6518,92 @@ def forward(self, y):
...
+                    else:
+                        return list(x)
+                return list(x)
+
+        x = torch.ones((3, 4), dtype=torch.double)
+        self.run_test(torch.jit.script(UninitializedTensorListModel()), x, input_names=["input_1"],
+                      dynamic_axes={"input_1": [0, 1]})
+
+    # onnx::Identity of sequence supported for ONNX opset >= 14
+    # ORT is not support this graph in version 14.
```
Comment (hwangdeyu) [inline test/onnx/test_pytorch_onnx_onnxruntime.py:6555]: Need check if the graph is vaild in ONNX

**Comment by hwangdeyu** [comment]
@neginraoof  https://github.com/pytorch/pytorch/pull/60534#discussion_r701456509
Yes, I have added this warning information.

File: test/onnx/test_pytorch_onnx_onnxruntime.py (hunk 13 above)
Comment (hwangdeyu) [reply test/onnx/test_pytorch_onnx_onnxruntime.py:6555]: It's valid.

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp [hunk 14]
```diff
@@ -256,25 +257,43 @@ bool IsUninitializedNode(Node* n) {
...
+      const_node->i_(attr::dtype, onnx_type);
+      const_node->output()->setType(other_output->type());
+    } else {
+      std::cerr
+          << "Warning: UninitializedOutput - Invalid elem Type of ListTensor found."
+          << std::endl;
+      const_node->output()->setType(other_output->type());
+    }
   }
   const_node->insertBefore(block->return_node());
```
Comment (jiafatom) [inline torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:298]: Probably we need add shape inference for this const node, like
```cpp
const ParamMap empty_params_dict = {};
auto opset_version =
        py::cast<int>(onnx_symbolic.attr("_export_onnx_opset_version"));
ONNXShapeTypeInference(const_node, empty_params_dict, opset_version);
```
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/onnx.cpp#L286

Comment (hwangdeyu) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:303]: > Probably we need add shape inference for this const node, like
> 
> ```c++
> const ParamMap empty_params_dict = {};
> auto opset_version =
>         py::cast<int>(onnx_symbolic.attr("_export_onnx_opset_version"));
> ONNXShapeTypeInference(const_node, empty_params_dict, opset_version);
> ```
> 
> https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/onnx.cpp#L286

Done, shape inference needed after `constant` node.

**Review by jiafatom — APPROVED** [review]
Nice job! Thanks!

File: torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp (hunk 14 above)
Comment (jiafatom) [reply torch/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp:303]: nit: It is better to move `const_node->insertBefore(block->return_node());` before shape inference logic. (although for const node it may be fine)

File: test/onnx/test_pytorch_onnx_onnxruntime.py [hunk 15]
```diff
@@ -6518,6 +6518,92 @@ def forward(self, y):
...
+                return list(x)
+
+        x = torch.ones((3, 4), dtype=torch.double)
+        self.run_test(torch.jit.script(UninitializedTensorListModel()), x, input_names=["input_1"],
+                      dynamic_axes={"input_1": [0, 1]})
+
+    # onnx::Identity of sequence supported for ONNX opset >= 14
+    @skipIfUnsupportedMinOpsetVersion(14)
+    @skipIfONNXShapeInference(False)
+    def test_uninitialized_intList(self):
```
Comment (BowenBao) [inline test/onnx/test_pytorch_onnx_onnxruntime.py:6557]: hi @hwangdeyu , this test starts to fail after syncing with latest master + onnx_ms_1 branch. Please take a look when you get a chance. I'll submit the PR to pytorch master with this test disabled.

Comment (jiafatom) [reply test/onnx/test_pytorch_onnx_onnxruntime.py:6557]: filed a work item: https://msdata.visualstudio.com/Vienna/_workitems/edit/1441852

Comment (BowenBao) [reply test/onnx/test_pytorch_onnx_onnxruntime.py:6557]: update: we discovered it is due to upstream torch IR graph changes that led to the regression. The initial int list creation is noe emitted as `prim::ListConstruct` instead of `prim::Loop`.
Test case is updated to preserve the previous expected IR graph. The item above can be used to track future support for the new IR graph.
