### PR TITLE
[ONNX] Add warning for inplace updates on tensor.shape in tracing mode

### LINKED ISSUE #56162: Tracer vs eager mode difference on tensor.shape
## 🐛 Bug

In eager mode, shape values obtained from tensor.shape are python int, so there are treated as different values. However in tracing both are traced as tensors, and then they share same memory. This causes mismatch in final outputs

## To Reproduce

```
# Tracer vs Eager mode difference in tensor.shape
import torch
import onnxruntime

class Model(torch.nn.Module):
    def forward(self, hidden_states):
        batch_size, seq_length = hidden_states.shape[:2]
        real_seq_length = seq_length
        real_seq_length += 2                                            => real_seq_length and seq_legth should have different values
        return real_seq_length + seq_length


# Call export

# hidden_states is tensor of rank 2
hidden_states = torch.randn(2, 3, 5)
model = Model()

import io
onnx_io = io.BytesIO()
tracemodel = torch.jit.trace(model, (hidden_states, ))
torch.onnx.export(model, (hidden_states, ), onnx_io, verbose=True)

# Call onnxruntime runtime and compare outputs on dynamic inputs
ort_session = onnxruntime.InferenceSession(onnx_io.getvalue())

print(model(hidden_states))
print(tracemodel(hidden_states))
print(ort_session.run(None, {
                                ort_session.get_inputs()[0].name: hidden_states.numpy()
                            }))
```

## Expected behavior

**Output in eager mode**
8 (real_seq_length(=3) + seq_length(=5))

**Output in tracing mode**
Should be 8 but is 10 (real_seq_length(=5) + seq_length(=5)) as tensors share same memory

**Graph output on exporting ONNX graph**
```
graph(%0 : Float(2, 3, 5, strides=[15, 5, 1], requires_grad=0, device=cpu)):
  %1 : Long(3, strides=[1], device=cpu) = onnx::Shape(%0)
  %2 : Long(device=cpu) = onnx::Constant[value={1}]()
  %3 : Long(device=cpu) = onnx::Gather[axis=0](%1, %2) # test/onnx/test_m.py:38:0
  %4 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={2}]()
  %5 : Long(requires_grad=0, device=cpu) = onnx::Add(%3, %4) # test/onnx/test_m.py:40:0
  %6 : Long(requires_grad=0, device=cpu) = onnx::Add(%5, %5) # test/onnx/test_m.py:41:0   ===> %5 proves that both seq_length and real_seq_length have same values/memory
  return (%6)
```

cc @gmagogsfm @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

### PR DESCRIPTION
**Pull request by shubhambhokare1**
Related to #56162

### CODE REVIEW

File: torch/csrc/jit/passes/remove_inplace_ops.cpp [hunk 1]
```diff
@@ -38,6 +38,22 @@ void ImplicitCastForBinaryInplaceOps(Block* b) {
       if (originalInputs.at(0) == originalInputs.at(1)) {
         continue;
       }
+
+      // Introduce warning for special case where shape values are obtained from
+      // tensor.shape In eager mode these values are python int, so there are
```
Comment (fatcat-z) [inline torch/csrc/jit/passes/remove_inplace_ops.cpp:43]: typo: so there are  => so they are

File: torch/csrc/jit/passes/remove_inplace_ops.cpp [hunk 2]
```diff
@@ -38,6 +38,22 @@ void ImplicitCastForBinaryInplaceOps(Block* b) {
...
+      // treated as different values. However in tracing both are traced as
+      // tensors, and then they share same memory. This causes a mismatch in
+      // final outputs
+      auto shape_node = originalInputs.at(0)->node();
+      if ((shape_node->kind() == prim::NumToTensor) &&
+          (shape_node->inputs().at(0)->node()->kind() == aten::size)) {
+        std::cerr
+            << "In tracing mode, shape values obtained from tensor.shape are traced as tensors, "
+            << "and share the same memory. This might causes a mismatch in final outputs. "
```
Comment (fatcat-z) [inline torch/csrc/jit/passes/remove_inplace_ops.cpp:52]: might causes => might cause

Comment (fatcat-z) [reply torch/csrc/jit/passes/remove_inplace_ops.cpp:52]: nit: May we clarify what kind of mismatch could be?

File: torch/csrc/jit/passes/remove_inplace_ops.cpp [hunk 3]
```diff
@@ -38,6 +38,22 @@ void ImplicitCastForBinaryInplaceOps(Block* b) {
...
+      // Introduce warning for special case where shape values are obtained from
+      // tensor.shape In eager mode these values are python int, so there are
+      // treated as different values. However in tracing both are traced as
+      // tensors, and then they share same memory. This causes a mismatch in
+      // final outputs
+      auto shape_node = originalInputs.at(0)->node();
+      if ((shape_node->kind() == prim::NumToTensor) &&
+          (shape_node->inputs().at(0)->node()->kind() == aten::size)) {
+        std::cerr
+            << "In tracing mode, shape values obtained from tensor.shape are traced as tensors, "
```
Comment (garymm) [inline torch/csrc/jit/passes/remove_inplace_ops.cpp:51]: I suggest we keep this very short here and just link to a longer explanation in onnx.html that includes example code.

File: torch/csrc/jit/passes/remove_inplace_ops.cpp [hunk 4]
```diff
@@ -38,6 +38,22 @@ void ImplicitCastForBinaryInplaceOps(Block* b) {
       if (originalInputs.at(0) == originalInputs.at(1)) {
         continue;
       }
+
+      // Introduce warning for special case where shape values are obtained from
```
Comment (garymm) [inline torch/csrc/jit/passes/remove_inplace_ops.cpp:42]: This comment is redundant with the content of the warning. Please remove it.

File: torch/csrc/jit/passes/remove_inplace_ops.cpp [hunk 5]
```diff
@@ -38,6 +38,22 @@ void ImplicitCastForBinaryInplaceOps(Block* b) {
...
+      // treated as different values. However in tracing both are traced as
+      // tensors, and then they share same memory. This causes a mismatch in
+      // final outputs
+      auto shape_node = originalInputs.at(0)->node();
+      if ((shape_node->kind() == prim::NumToTensor) &&
+          (shape_node->inputs().at(0)->node()->kind() == aten::size)) {
+        std::cerr
+            << "In tracing mode, shape values obtained from tensor.shape are traced as tensors, "
+            << "and share the same memory. This might causes a mismatch in final outputs. "
+            << "As a workaround, avoid use of inplace operations in these scenarios. "
```
Comment (garymm) [inline torch/csrc/jit/passes/remove_inplace_ops.cpp:53]: Remove extra space at the end

File: torch/csrc/jit/passes/remove_inplace_ops.cpp [hunk 6]
```diff
@@ -38,6 +38,22 @@ void ImplicitCastForBinaryInplaceOps(Block* b) {
...
+
+      // Introduce warning for special case where shape values are obtained from
+      // tensor.shape In eager mode these values are python int, so there are
+      // treated as different values. However in tracing both are traced as
+      // tensors, and then they share same memory. This causes a mismatch in
+      // final outputs
+      auto shape_node = originalInputs.at(0)->node();
+      if ((shape_node->kind() == prim::NumToTensor) &&
+          (shape_node->inputs().at(0)->node()->kind() == aten::size)) {
+        std::cerr
```
Comment (garymm) [inline torch/csrc/jit/passes/remove_inplace_ops.cpp:50]: Should we use JIT_LOG rather than write to std::cerr directly?
What are the trade-offs?

**Review by garymm — CHANGES_REQUESTED** [review]
Thanks!

**Comment by garymm** [comment]
Assigning @fatcat-z as per the on-duty instructions.

**Comment by neginraoof** [comment]
Just to clarify this change for myself, why do we need this change in ImplicitCastForBinaryInplaceOps?
I mean does it cause a mismatch when we cast inputs in such a situation?

File: torch/csrc/jit/passes/remove_inplace_ops.cpp (hunk 3 above)
Comment (shubhambhokare1) [reply torch/csrc/jit/passes/remove_inplace_ops.cpp:51]: Would this go in the Frequently asked questions section?

**Comment by shubhambhokare1** [comment]
> Just to clarify this change for myself, why do we need this change in ImplicitCastForBinaryInplaceOps?
> I mean does it cause a mismatch when we cast inputs in such a situation?

I added this check in this function to avoid duplication of code. No, this particular scenario does not occur only in the case, it  may happen for other general cases. If it makes sense, I can create another function to handle just this particular check.

File: torch/csrc/jit/passes/remove_inplace_ops.cpp (hunk 3 above)
Comment (shubhambhokare1) [reply torch/csrc/jit/passes/remove_inplace_ops.cpp:51]: Would this go in the FAQ section?

Comment (garymm) [reply torch/csrc/jit/passes/remove_inplace_ops.cpp:51]: "Avoiding Pitfalls" or "Limitations" seem better to me. I can't imagine someone actually asking about this unless they see this warning, so it won't be a frequently asked question.

File: torch/csrc/jit/passes/remove_inplace_ops.cpp (hunk 6 above)
Comment (shubhambhokare1) [reply torch/csrc/jit/passes/remove_inplace_ops.cpp:121]: It seems like  JIT_LOG more for cases such as graph updates/transformations and node deletions. I think it would make more sense to write to std::cerr as we are not necessarily updating any aspect of the graph.

File: torch/csrc/jit/passes/remove_inplace_ops.cpp [hunk 7]
```diff
@@ -112,6 +112,16 @@ void ImplicitCastForBinaryInplaceOps(Block* b) {
       if (originalInputs.at(0) == originalInputs.at(1)) {
         continue;
       }
+
+      auto shape_node = originalInputs.at(0)->node();
+      if ((shape_node->kind() == prim::NumToTensor) &&
+          (shape_node->inputs().at(0)->node()->kind() == aten::size)) {
+        std::cerr
+            << "In tracing mode, shape values obtained from tensor.shape might cause a mismatch "
```
Comment (garymm) [inline torch/csrc/jit/passes/remove_inplace_ops.cpp:120]: I'd replace this with a very short text and the URL of the doc you added.

Maybe:
"In-place op on output of tensor.shape. See https://pytorch.org/docs/master/onnx.html#..."

Also, any way to indicate the source location (file name and line)?

**Review by garymm — CHANGES_REQUESTED** [review]
Thanks

**Review by garymm — APPROVED** [review]
